---

- name: create DNS zone for demo
  community.general.ipa_dnszone:
    ipa_host: "{{ idm_host }}"
    ipa_pass: "{{ idm_password }}"
    validate_certs: "{{ idm_validate_certs | default(false) }}"
    zone_name: "{{ demo_uuid }}.{{ base_dns_suffix }}"
    state: "{{ demo_context_state | default('present') }}"