---

- name: include tasks to create context
  ansible.builtin.include_tasks:
    file: "{{ task_file }}"
  loop_control:
    loop_var: task_file
  loop:
    - netbox-tenant.yml
    - vcenter-folder.yml
    - dns-zone.yml
    - satellite-subnet.yml