---

- name: manage tenant in netbox
  netbox.netbox.netbox_tenant:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ (netbox_validate_certs | bool) | default(omit) }}"
    data:
      name: "{{ audience }} - {{ demo }}"
    state: "{{ demo_context_state }}"
