---

- name: manage vm entry in cmdb
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ (netbox_validate_certs | bool) | default(omit) }}"
    data:
      name: "{{ inventory_hostname }}"
      vcpus: "{{ cpus | float }}"
      memory: "{{ memory_mb }}"
      disk: 100
      tenant: "{{ demo_uuid }}"
      cluster: "{{ vcenter_cluster }}"
      primary_ip4: "{{ allocated_ip_address.ip_address | default(omit) }}"
  register: vm_record_created

- name: add interface to vm in cmdb
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ (netbox_validate_certs | bool) | default(omit) }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: ens192
      mtu: 1500