---

- name: add additional storage to the VM
  block:
    - name: search for VM
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ vcenter.server }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_validate_certs: no
        filter_names: "{{ inventory_hostname }}"
      register: vm_search_results
    - name: get VM info
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ vcenter.server }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_validate_certs: no
        vm: "{{ vm_search_results.value[0].vm }}"
      register: vm_info
    - name: attach a new disk
      vmware.vmware_rest.vcenter_vm_hardware_disk:
        vcenter_hostname: "{{ vcenter.server }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_validate_certs: no
        vm: "{{ vm_info.id }}"
        type: "{{ new_disk.type }}"
        new_vmdk:
          capacity: "{{ new_disk.capacity }}"
        scsi:
          bus: "{{ new_disk.scsi.bus }}"
          unit: "{{ new_disk.scsi.unit }}"
      loop_control:
        loop_var: new_disk
      loop: "{{ additional_storage }}"
      ignore_errors: "{{ ignore_virtual_disk_errors | default('no') }}"
  delegate_to: "{{ delegate_host }}"
  