---

- name: get access token using offline token
  ansible.builtin.uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ console_dot_offline_token }}"
  register: api_authentication
- name: set api token fact
  ansible.builtin.set_fact:
    console_dot_api_access_token: "{{ api_authentication.json.access_token }}"