---

- name: set initial settings
  redhat.satellite.foreman_setting:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    name: "{{ setting.name }}"
    value: "{{ setting.value }}"
  loop_control:
    loop_var: setting
  loop: "{{ satellite.foreman_settings }}"
  delegate_to: "{{ delegate_host }}"

