---

- name: configure satellite organizations
  redhat.satellite.organization:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    name: "{{ organization.name }}"
    state: "{{ organization.state | default(omit) }}"
  loop_control:
    loop_var: organization
  loop: "{{ satellite.foreman.organizations }}"
  delegate_to: "{{ delegate_host }}"
