---

- name: set initial settings
  redhat.satellite.setting:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    name: "{{ setting.name }}"
    value: "{{ setting.value }}"
  loop_control:
    loop_var: setting
  loop: "{{ satellite | json_query('foreman.settings') }}"
  when:
    - satellite.foreman.settings is defined
  delegate_to: "{{ delegate_host }}"
