---

hub_install:
  admin_password: "{  { admin_password }}"
  pg:
    password: "{  { admin_password }}"

ah_host: "{  { inventory_hostname }}"
ah_username: "{  { admin_username }}"
ah_password: "{  { admin_password }}"
ah_validate_certs: no