---

- name: Demo Provisioner Peripheral Credentials
  kind: cloud
  inputs:
    fields:
      - id: dns_pass
        type: string
        label: dns_pass
        secret: yes
      - id: ansible_password
        type: string
        label: ansible_password
        secret: yes
      - id: satellite_password
        type: string
        label: satellite_password
        secret: yes
      - id: vcenter_password
        type: string
        label: vcenter_password
        secret: yes
      - id: controller_hostname
        type: string
        label: controller_hostname
      - id: controller_username
        type: string
        label: controller_username
      - id: controller_password
        type: string
        label: controller_password
        secret: yes
      - id: crhc_username
        type: string
        label: crhc_username
      - id: crhc_password
        type: string
        label: crhc_password
        secret: yes
      - id: hub_username
        type: string
        label: hub_username
      - id: hub_password
        type: string
        label: hub_password
        secret: yes
  injectors:
    extra_vars:
      dns_pass: "{  { dns_pass }}"
      ansible_password: "{  { ansible_password }}"
      satellite_password: "{  { satellite_password }}"
      vcenter_password: "{  { vcenter_password }}"
      controller_hostname: "{  { controller_hostname }}"
      controller_username: "{  { controller_username }}"
      controller_password: "{  { controller_password }}"
      controller_validate_certs: "no"
      crhc_username: "{  { crhc_username }}"
      crhc_password: "{  { crhc_password }}"
      hub_username: "{  { hub_username }}"
      hub_password: "{  { hub_password }}"