---

controller_credential_types:

  - name: Demo Provisioner Admin Credentials
    kind: cloud
    inputs:
      fields:
        - id: admin_username
          type: string
          label: Admin Username
        - id: admin_password
          type: string
          label: Admin Password
          secret: yes
    injectors:
      extra_vars:
        admin_username: "{  { admin_username }}"
        admin_password: "{  { admin_password }}"

  - name: Demo Provisioner Controller Credentials
    kind: cloud
    inputs:
      fields:
        - id: controller_hostname
          type: string
          label: Controller Hostname
        - id: controller_username
          type: string
          label: Controller Username
        - id: controller_password
          type: string
          label: Controller Password
          secret: yes
    injectors:
      extra_vars:
        controller_hostname: "{  { controller_hostname }}"
        controller_username: "{  { controller_username }}"
        controller_password: "{  { controller_password }}"
        controller_validate_certs: "no"

  - name: Demo Provisioner Netbox Credentials
    kind: cloud
    inputs:
      fields:
        - id: netbox_url
          type: string
          label: Netbox URL
        - id: netbox_username
          type: string
          label: Netbox Username
        - id: netbox_password
          type: string
          label: Netbox Password
          secret: yes
    injectors:
      extra_vars:
        netbox_url: "{  { netbox_url }}"
        netbox_username: "{  { netbox_username }}"
        netbox_password: "{  { netbox_password }}"
        netbox_validate_certs: "no"

  - name: Demo Provisioner vCenter Credentials
    kind: cloud
    inputs:
      fields:
        - id: vcenter_hostname
          type: string
          label: vCenter Hostname
        - id: vcenter_username
          type: string
          label: vCenter Username
        - id: vcenter_password
          type: string
          label: vCenter Password
          secret: yes
        - id: vcenter_datacenter
          type: string
          label: vCenter Datacenter
        - id: vcenter_cluster
          type: string
          label: vCenter Cluster
    injectors:
      extra_vars:
        vcenter_hostname: "{  { vcenter_hostname }}"
        vcenter_username: "{  { vcenter_username }}"
        vcenter_password: "{  { vcenter_password }}"
        vcenter_validate_certs: "no"
        vcenter_datacenter: "{  { vcenter_datacenter }}"
        vcenter_cluster: "{  { vcenter_cluster }}"

  - name: Demo Provisioner IDM Credentials
    kind: cloud
    inputs:
      fields:
        - id: idm_host
          type: string
          label: IDM Host
        - id: idm_password
          type: string
          label: IDM Password
          secret: yes
    injectors:
      extra_vars:
        idm_host: "{  { idm_host }}"
        idm_password: "{  { idm_password }}"
        idm_validate_certs: "no"

  - name: Demo Provisioner Satellite Credentials
    kind: cloud
    inputs:
      fields:
        - id: satellite_url
          type: string
          label: Satellite URL
        - id: satellite_username
          type: string
          label: Satellite Username
        - id: satellite_password
          type: string
          label: Satellite Password
          secret: yes
        - id: satellite_organization
          type: string
          label: Satellite Organization
        - id: satellite_location
          type: string
          label: Satellite Location
    injectors:
      extra_vars:
        satellite_url: "{  { satellite_url }}"
        satellite_username: "{  { satellite_username }}"
        satellite_password: "{  { satellite_password }}"
        satellite_validate_certs: "no"
        satellite_organization: "{  { satellite_organization }}"
        satellite_location: "{  { satellite_location }}"
      env:
        XDG_CACHE_HOME: /tmp/.cache

  - name: Demo Provisioner Red Hat Registry Credentials
    kind: cloud
    inputs:
      fields:
        - id: redhat_registry_username
          type: string
          label: Red Hat Registry Username
        - id: redhat_registry_password
          type: string
          label: Red Hat Registry Password
          secret: yes
    injectors:
      extra_vars:
        redhat_registry_username: "{  { redhat_registry_username }}"
        redhat_registry_password: "{  { redhat_registry_password }}"

  - name: Demo Provisioner EE Python Libraries Env Vars
    kind: cloud
    injectors:
      env:
        XDG_CACHE_HOME: /tmp/.cache

  - name: Demo Provisioner Console Dot Offline Token
    kind: cloud
    inputs:
      fields:
        - id: console_dot_offline_token
          type: string
          label: Console Dot Offline Token
          secret: yes
    injectors:
      extra_vars:
        console_dot_offline_token: "{  { console_dot_offline_token }}"
