---

- name: Demo Provisioner Admin Credentials
  credential_type: Demo Provisioner Admin Credentials
  organization: "{{ controller_organization }}"
  inputs:
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"

- name: Demo Provisioner Controller Credentials
  credential_type: Demo Provisioner Controller Credentials
  organization: "{{ controller_organization }}"
  inputs:
    controller_hostname: "{{ controller.hostname }}"
    controller_username: "{{ controller.username }}"
    controller_password: "{{ controller.password }}"

- name: Demo Provisioner Netbox Credentials
  credential_type: Demo Provisioner Netbox Credentials
  organization: "{{ controller_organization }}"
  inputs:  
    netbox_url: "{{ netbox.url }}"
    netbox_username: "{{ netbox.username }}"
    netbox_password: "{{ netbox.password }}"

- name: Demo Provisioner vCenter Credentials
  credential_type: Demo Provisioner vCenter Credentials
  organization: "{{ controller_organization }}"
  inputs:
    vcenter_hostname: "{{ vcenter.hostname }}"
    vcenter_username: "{{ vcenter.username }}"
    vcenter_password: "{{ vcenter.password }}"
    vcenter_datacenter: "{{ vcenter.datacenter }}"
    vcenter_cluster: "{{ vcenter.cluster }}"

- name: Demo Provisioner IDM Credentials
  credential_type: Demo Provisioner IDM Credentials
  organization: "{{ controller_organization }}"
  inputs:
    idm_host: "{{ idm.host }}"
    idm_password: "{{ idm.password }}"

- name: Demo Provisioner Root Account
  credential_type: Machine
  organization: "{{ controller_organization }}"
  inputs:
    username: root
    password: "{{ admin_password }}"

- name: Demo Provisioner Satellite Credentials
  credential_type: Demo Provisioner Satellite Credentials
  organization: "{{ controller_organization }}"
  inputs:
    satellite_url: "{{ satellite.url }}"
    satellite_username: "{{ satellite.username }}"
    satellite_password: "{{ satellite.password }}"
    satellite_organization: "{{ satellite.organization }}"
    satellite_location: "{{ satellite.location }}"

- name: Demo Provisioner Red Hat Registry Credentials
  credential_type: Demo Provisioner Red Hat Registry Credentials
  organization: "{{ controller_organization }}"
  inputs:
    redhat_registry_username: "{{ redhat_registry.username }}"
    redhat_registry_password: "{{ redhat_registry.password }}"

- name: Demo Provisioner Local Administrator
  organization: "{{ controller_organization }}"
  credential_type: Machine
  inputs:
    username: Administrator
    password: "{{ admin_password }}"

- name: Demo Provisioner Domain Administrator
  organization: "{{ controller_organization }}"
  credential_type: Machine
  inputs:
    username: AD\Administrator
    password: "{{ admin_password }}"

- name: Demo Provisioner EE Image Registry Credentials
  organization: "{{ controller_organization }}"
  credential_type: Container Registry
  inputs:
    host: "{{ ee_registry.host }}"
    username: "{{ ee_registry.username }}"
    password: "{{ ee_registry.password }}"
    verify_ssl: "{{ ee_registry.verify_ssl | bool }}"

- name: Demo Provisioner EE Python Libraries Env Vars
  organization: "{{ controller_organization }}"
  credential_type: Demo Provisioner EE Python Libraries Env Vars