---

- name: "{{ demo_prefix }} Provisioner Credentials"
  credential_type: "Demo Provisioner Peripheral Credentials"
  organization: "{{ controller_organization }}"
  inputs:
    dns_pass: "{{ dns_pass }}"
    ansible_password: "{{ ansible_password }}"
    satellite_password: "{{ satellite_password }}"
    vcenter_password: "{{ vcenter_password }}"
    controller_hostname: "{{ controller.hostname }}"
    controller_username: "{{ controller.username }}"
    controller_password: "{{ controller.password }}"
    crhc_username: "{{ crhc_username }}"
    crhc_password: "{{ crhc_password }}"
- name: "{{ demo_prefix }} Root Account"
  credential_type: Machine
  organization: "{{ controller_organization }}"
  inputs:
    username: root
    password: "{{ ansible_password }}"