---

lifecycle_environment: production
provisioning:
  host_group: "{  { os }}/vlan146"
  method: bootdisk
  dns_domain: "{  { demo_uuid }}.{  { base_dns_suffix }}"
  cpus: "{  { cpus }}"
  memory_mb: "{  { memory_mb }}"
  activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"
run_additional_roles: no
