---

- name: "{{ controller.hostname }}"
  inventory: "{{ demo_prefix }} Infrastructure"
  variables: "{{ lookup('file', controller.configuration_file) | from_yaml }}"
- name: "{{ satellite.hostname }}"
  inventory: "{{ demo_prefix }} Infrastructure"
  variables: "{{ lookup('file', satellite.configuration_file) | from_yaml }}"