---

network_prefix: 10.15.120.0/22

base_dns_suffix: demos.lcl

config_files:
  - hosts
  - resolv.conf

timesync_ntp_servers:
  - hostname: 0.rhel.pool.ntp.org
    iburst: yes
  - hostname: 1.rhel.pool.ntp.org
    iburst: yes
  - hostname: 2.rhel.pool.ntp.org
    iburst: yes
  - hostname: 3.rhel.pool.ntp.org
    iburst: yes

selinux_policy: targeted
selinux_state: permissive

dns_resolv:
  search_domains:
    - "{  { demo_uuid }}.{{ base_dns_suffix }}"
    - lab.msp.redhat.com
  nameservers:
    - 10.15.108.102
    - 10.15.108.101
  options:
    - 'timeout:1'
base_packages:
  disable_gpg_check: yes
  packages:
    - lsof
    - vim
    - sos
    - redhat-support-tool
    - open-vm-tools
ignore_virtual_disk_errors: yes
remove_cdrom: no