---

dns_zone: demos.lab.msp.redhat.com
dns:
  server: idm.lab.msp.redhat.com
  password: "{  { dns_pass }}"
  records:
    - name: "{  { inventory_hostname.split('.')[0] }}"
      zone: demos.lab.msp.redhat.com
      type: A
      value: "{  { ip_address }}"
    - name: "{  { ip_address.split('.')[-1] }}"
      zone: "{  { ip_address.split('.')[2] }}.15.10.in-addr.arpa."
      type: PTR
      value: "{  { inventory_hostname }}."
config_files:
  - hosts
  - resolv.conf
timesync_ntp_servers:
  - hostname: 0.rhel.pool.ntp.org
    iburst: yes
  - hostname: 1.rhel.pool.ntp.org
    iburst: yes
  - hostname: 2.rhel.pool.ntp.org
    iburst: yes
  - hostname: 3.rhel.pool.ntp.org
    iburst: yes
vcenter:
  server: vcenter02.lab.msp.redhat.com
  username: 'Administrator@vsphere.local'
  password: "{  { vcenter_password }}"
  datacenter: MSP Lab
selinux_policy: targeted
selinux_state: permissive
dns_resolv:
  search_domains:
    - josh.lab.msp.redhat.com
    - lab.msp.redhat.com
  nameservers:
    - 10.15.120.4
    - 10.15.108.5
  options:
    - 'timeout:1'
base_packages:
  disable_gpg_check: yes
  packages:
    - lsof
    - vim
    - sos
    - redhat-support-tool
ignore_virtual_disk_errors: yes
remove_cdrom: no