---

- name: Provision Demo
  organization: "{{ controller_organization }}"
  state: "{{ controller_state | default('present') }}"
  survey_enabled: yes
  survey:
    name: ''
    description: ''
    spec:
      - type: multiplechoice
        question_name: Which Demo?
        question_description: What demo should be provisioned?
        variable: demo
        choices:
          - patching
          - s4hana-deployment
          - compliance
          - idm-ad
        required: yes
      - type: text
        question_name: "Demo Audience?"
        question_description: "Who is the audience for this demo?"
        variable: audience
        required: yes
      - type: text
        question_name: "Provisioner?"
        question_description: "Who is provisioning this demo?"
        variable: provisioner
        required: yes
        default: 'Josh Swanson'
      - type: text
        question_name: "Provisioner's Email?"
        question_description: "What is the provisioner's email address?"
        variable: provisioner_email
        required: yes
        default: 'joshswanson@redhat.com'
  extra_vars:
    demo_context_state: present
  simplified_workflow_nodes:
    - identifier: Configure Demo Context
      unified_job_template: Configure Demo Context
      credentials:
        - Demo Provisioner Netbox Credentials
        - Demo Provisioner vCenter Credentials
      success_nodes:
        - Run Demo Provisioner Workflow
    - identifier: Configure Demo Inventory
      unified_job_template: Configure Demo Inventory
      credentials:
        - Demo Provisioner Controller Credentials
      success_nodes:
        - Run Demo Provisioner Workflow
    - identifier: Run Demo Provisioner Workflow
      unified_job_template: Run Demo Provisioner Workflow
      all_parents_must_converge: yes
      credentials:
        - Demo Provisioner Controller Credentials
