---

# - name: Provision Demo
#   organization: "{{ controller_organization }}"
#   state: "{{ controller_state | default('present') }}"
#   survey_enabled: yes
#   survey:
#     name: ''
#     description: ''
#     spec:
#       - type: multiplechoice
#         question_name: Which Demo?
#         question_description: What demo should be provisioned?
#         variable: demo
#         choices:
#           - patching
#           - s4hana-deployment
#           - compliance
#           - idm-ad
#         required: yes
#       - type: text
#         question_name: "Demo Audience?"
#         question_description: "Who is the audience for this demo?"
#         variable: audience
#         required: yes
#       - type: text
#         question_name: "Provisioner?"
#         question_description: "Who is provisioning this demo?"
#         variable: provisioner
#         required: yes
#         default: 'Josh Swanson'
#       - type: text
#         question_name: "Provisioner's Email?"
#         question_description: "What is the provisioner's email address?"
#         variable: provisioner_email
#         required: yes
#         default: 'joshswanson@redhat.com'
#       - type: text
#         question_name: "Demo UUID?"
#         question_description: "If this demo exists, what is the unique ID?"
#         variable: demo_uuid
#         required: no
#   extra_vars:
#     demo_context_state: present
#   simplified_workflow_nodes:
#     - identifier: Setup Demo Context and Run Provisioner Workflow
#       unified_job_template: Configure Demo Inventory
#       credentials:
#         - Demo Provisioner Controller Credentials
#       success_nodes:
#         - Run Demo Provisioner Workflow
#     - identifier: Run Demo Provisioner Workflow
#       unified_job_template: Run Demo Provisioner Workflow
#       all_parents_must_converge: yes
#       credentials:
#         - Demo Provisioner Controller Credentials

- name: Teardown Demo
  organization: "{{ controller_organization }}"
  state: "{{ controller_state | default('present') }}"
  allow_simultaneous: yes
  survey_enabled: yes
  survey:
    name: ''
    description: ''
    spec:
      - type: multiplechoice
        question_name: Which Demo?
        question_description: What demo should be torn down?
        variable: demo
        choices:
          - patching
          - s4hana-deployment
          - compliance
          - idm-ad
          - aap-aa
        required: yes
      - type: text
        question_name: "Demo Audience?"
        question_description: "Who was the audience for this demo?"
        variable: audience
        required: yes
      - type: text
        question_name: "Provisioner?"
        question_description: "Who was provisioning this demo?"
        variable: provisioner
        required: yes
        default: 'Josh Swanson'
      - type: text
        question_name: "Provisioner's Email?"
        question_description: "What was the provisioner's email address?"
        variable: provisioner_email
        required: yes
        default: 'joshswanson@redhat.com'
      - type: text
        question_name: "Demo UUID?"
        question_description: "What is the UUID of the demo to tear down?"
        variable: demo_uuid
        required: yes
  extra_vars:
    demo_state: absent
    demo_context_state: absent
  simplified_workflow_nodes:
    - identifier: Run Demo Provisioner Workflow
      unified_job_template: Run Demo Provisioner Workflow
      credentials:
        - Demo Provisioner Controller Credentials
      success_nodes:
        - Remove Demo Inventory
      extra_data:
        wait_for_workflow: yes
    - identifier: Remove Demo Inventory
      unified_job_template: Remove Demo Inventory
      credentials:
        - Demo Provisioner Controller Credentials