---

- name: ensure rsync is installed
  ansible.builtin.yum:
    name: rsync

- name: ensure working directory exists
  ansible.builtin.file:
    path: "{{ demo_ansible_collections_working_directory }}"
    state: directory
