---

cpus: 4
memory_mb: 16384
os: rhel8
application: general

aap_download_url: http://satellite.lab.msp.redhat.com/pub/ansible-automation-platform-setup-2.1.2-1.tar.gz
aap_bundle: ansible-automation-platform-setup-2.1.2-1.tar.gz