---

roles:
  - name: linux-system-roles.cockpit
    source: https://galaxy.ansible.com
  - name: linux-system-roles.metrics
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hostagent
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hana_deployment
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_s4hana_deployment
    source: https://galaxy.ansible.com
  - name: sap-hana-hsr
    src: https://github.com/jjaswanson4/sap-hana-hsr/archive/refs/tags/v1.3.0.tar.gz
  - name: sap-hana-ha-pacemaker
    src: https://github.com/jjaswanson4/sap-hana-ha-pacemaker/archive/refs/tags/v2.0.0.tar.gz

collections:
  # "core" ansible collections
  - name: community.general
  - name: ansible.posix
  - name: jjaswanson4.utilities

  # windows ansible collections
  - name: ansible.windows
  - name: community.windows

  # vmware ansible collections
  - name: vmware.vmware_rest
  - name: community.vmware

  # rhel ansible collections
  - name: redhat.rhel_system_roles

  # satellite ansible collections
  - name: redhat.satellite
  - name: jjaswanson4.setup_rhel_for_satellite
  - name: jjaswanson4.install_satellite
    version: 1.2.7
  - name: jjaswanson4.configure_satellite
  
  # controller ansible collections
  - name: awx.awx
  - name: redhat_cop.controller_configuration

  # sap ansible collections
  - name: sap.rhel

  # netbox collections
  - name: netbox.netbox