---

roles:
  - name: linux-system-roles.cockpit
  - name: linux-system-roles.metrics
  # https://github.com/linux-system-roles/timesync/pull/134
  - name: linux-system-roles.timesync
  - name: redhat_sap.sap_hostagent
  - name: redhat_sap.sap_hana_deployment
  - name: redhat_sap.sap_s4hana_deployment
  - name: sap-hana-hsr
    src: https://github.com/jjaswanson4/sap-hana-hsr/archive/refs/tags/v1.3.0.tar.gz
  - name: sap-hana-ha-pacemaker
    src: https://github.com/jjaswanson4/sap-hana-ha-pacemaker/archive/refs/tags/v2.0.0.tar.gz

collections:
  # "core" ansible collections
  - name: community.general
  - name: ansible.posix
  - name: jjaswanson4.utilities

  # windows ansible collections
  - name: ansible.windows
  - name: community.windows

  # vmware ansible collections
  - name: vmware.vmware_rest
  - name: community.vmware

  # rhel ansible collections
  - name: redhat.rhel_system_roles

  # satellite ansible collections
  - name: redhat.satellite
  - name: jjaswanson4.setup_rhel_for_satellite
  - name: jjaswanson4.install_satellite
    version: '>=1.2.7'
  - name: jjaswanson4.configure_satellite
    version: '>=2.2.0'
  
  # controller ansible collections
  - name: ansible.controller
  - name: redhat_cop.controller_configuration

  # hub ansible collections
  - name: redhat_cop.ah_configuration
  - name: jjaswanson4.ah_configuration

  # sap ansible collections
  - name: sap.rhel
  - name: redhat.sap_install

  # netbox collections
  - name: netbox.netbox

  # IDM collections
  - name: redhat.rhel_idm

  # Podman collections
  - name: containers.podman
