---

- name: include kiosk tasks
  ansible.builtin.include_tasks:
    file: kiosk-config.yml

- name: flush handlers
  meta: flush_handlers

- name: include kiosk post tasks
  ansible.builtin.include_tasks:
    file: kiosk-post.yml
