---

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: import grab-assets tasks
  ansible.builtin.import_tasks: grab-assets.yml

- name: import push-configs tasks
  ansible.builtin.import_tasks: push-configs.yml

- name: import update image tasks
  ansible.builtin.import_tasks: update-installer-image.yml

- name: import push installer iso to datastore
  ansible.builtin.import_tasks: upload-installer-image.yml