---

- name: ensure podman is present
  ansible.builtin.dnf:
    name: podman

- name: create working directory
  ansible.builtin.file:
    path: "/tmp/{{ source_installer_image }}"
    state: directory
    mode: '0777'

- name: ensure /tmp is big enough
  community.general.lvol:
    vg: os
    lv: tmp
    size: 24g
    resizefs: yes

- name: ensure /var is big enough
  community.general.lvol:
    vg: os
    lv: var
    size: 24g
    resizefs: yes

- name: ensure / is big enough
  community.general.lvol:
    vg: os
    lv: root
    size: 12g
    resizefs: yes

# dirty workaround since vmware_copy module doesn't work
- name: install nfs-utils
  ansible.builtin.dnf:
    name: nfs-utils
  