---

- name: ensure podman is present
  ansible.builtin.dnf:
    name: podman

- name: create working directory
  ansible.builtin.file:
    path: /tmp/fleet_iso
    state: directory
    mode: '0777'

- name: ensure /tmp is big enough
  community.general.lvol:
    vg: os
    lv: tmp
    size: 16g
    resizefs: yes
  register: lv_grown

# dirty workaround since vmware_copy module doesn't work
- name: install nfs-utils
  ansible.builtin.dnf:
    name: nfs-uitls
  