---

- name: add configs to edge installer iso
  containers.podman.podman_container:
    name: "fleet-iso-util-{{ source_installer_image }}"
    image: quay.io/fleet-management/fleet-iso-util:latest
    state: started
    interactive: yes
    rm: yes
    volumes:
      - "/tmp/{{ source_installer_image }}:/isodir:Z"
    detach: no

