---

- name: grab iso from utility server
  ansible.builtin.fetch:
    src: /tmp/fleet_iso/fleet_out.iso
    dest: "/tmp/{{ demo_uuid }}-edge-installer.iso"

- name: upload edge installer ISO to datastore
  community.vmware.vsphere_copy:
    hostname: "{{ vcenter_hostname }}"
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: "{{ vcenter_validate_certs }}"
    src: "/tmp/{{ demo_uuid }}-edge-installer.iso"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vcenter_datastore }}"
    path: iso/
  delegate_to: localhost