---

galaxy_info:
  author: Josh Swanson
  description: manages DNS records in an IPA/IDM environment
  license: GPL-3.0
  min_ansible_version: 2.9
  galaxy_tags:
    - idm
    - ipa
    - dns
    - a_records
    - ptr_records

dependencies: []