---

- name: disable the screensaver
  ansible.builtin.shell:
    cmd: gsettings set org.gnome.desktop.session idle-delay 0
  listen:
     - disable_screensaver

- name: reboot system
  ansible.builtin.reboot:
    reboot_command: systemctl reboot
  listen:
    - reboot_system