---

- name: create kiosk users group
  ansible.builtin.group:
    name: kiosk-users
    gid: 2048
  notify:
    - reboot_system
    - disable_screensaver

- name: create kiosk user
  ansible.builtin.user:
    name: kiosk-user
    uid: 2048
    group: kiosk-users
    password: '$6$R3dh4t123$cYAI8okOB5I/cozPAatzNBBPwKOhnEAxaseIaTKuQWcYg.Js2ce3ZCtRK/nj9wmIBc17Y3e/Jm2Do/r6CBvwG/'
  notify:
    - reboot_system
    - disable_screensaver

- name: enable auto-login for kiosk user
  ansible.builtin.blockinfile:
    path: /etc/gdm/custom.conf
    insertafter: '\[daemon\]'
    block: |
      AutomaticLoginEnable=True
      AutomaticLogin=kiosk-user
  notify:
    - reboot_system
    - disable_screensaver

- name: configure kiosk-user to use the kiosk session
  ansible.builtin.blockinfile:
    path: /var/lib/AccountsService/users/kiosk-user
    insertafter: '\[User\]'
    create: yes
    block: |
      Session=com.redhat.Kiosk
      SystemAccount=false
  notify:
    - reboot_system
    - disable_screensaver

- name: create kiosk service file
  ansible.builtin.template:
    src: templates/kiosk.service.j2
    dest: /etc/systemd/system/kiosk.service
  notify:
    - reboot_system
    - disable_screensaver

- name: enable the service
  ansible.builtin.systemd:
    name: kiosk.service
    enabled: yes
  notify:
    - reboot_system
    - disable_screensaver
