---

- name: grab rhc status
  ansible.builtin.shell:
    cmd: rhc status
  register: rhc_status
  changed_when: false

- name: print out rhc status
  ansible.builtin.debug:
    msg: "{{ rhc_status.stdout }}"

- name: trigger run of insights-client
  ansible.builtin.shell:
    cmd: insights-client
  register: insights_client_run

- name: print out insights info
  ansible.builtin.debug:
    msg: "{{ insights_client_run.stdout }}"

- name: check the status of the system
  ansible.builtin.shell:
    cmd: rpm-ostree status
  register: rpm_ostree_status
  
- name: print out rpm-ostree status
  ansible.builtin.debug:
    msg: "{{ rpm_ostree_status.stdout_lines }}"