---



aap_download_url: http://satellite.lab.msp.redhat.com/pub/ansible-automation-platform-setup-2.1.0-1.tar.gz
aap_bundle: ansible-automation-platform-setup-2.1.0-1.tar.gz

controller_install:
  admin_password: "{  { admin_password }}"
  pg:
    password: "{  { admin_password }}"

bootstrap_controller: yes

controller_hostname: "{  { inventory_hostname }}"
controller_username: "{  { admin_username }}"
controller_password: "{  { admin_password }}"
controller_validate_certs: no

controller_configuration_projects_async_delay: 10

setup_hub_credentials: yes
automation_hub:
  url: "https://{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}"
  username: "{  { admin_username }}"
  password: "{  { admin_password }}"
  validate_certs: no

controller_license:
  manifest: /tmp/controller-manifest.zip

controller_settings:
  - name: GALAXY_IGNORE_CERTS
    value: "true"
  - name: AWX_TASK_ENV
    value: 
      GIT_SSL_NO_VERIFY: 'True'
    

controller_organizations:
  - name: "{  { audience }}"
    galaxy_credentials:
      - "{  { audience }} Automation Hub Credentials"
      - Ansible Galaxy

controller_credential_types:
  - name: Ansible Controller Credentials
    kind: cloud
    inputs:
      fields:
        - id: controller_hostname
          type: string
          label: Controller Hostname
        - id: controller_username
          type: string
          label: Controller Username
        - id: controller_password
          type: string
          label: Controller Password
          secret: yes
    injectors:
      extra_vars:
        controller_hostname: "{  { inventory_hostname }}"
        controller_username: "{  { controller_username }}"
        controller_password: "{  { controller_password }}"
        controller_validate_certs: "no"
  - name: Netbox Credentials
    kind: cloud
    inputs:
      fields:
        - id: netbox_url
          type: string
          label: Netbox URL
        - id: netbox_username
          type: string
          label: Netbox Username
        - id: netbox_password
          type: string
          label: Netbox Password
          secret: yes
    injectors:
      extra_vars:
        netbox_url: "{  { netbox_url }}"
        netbox_username: "{  { netbox_username }}"
        netbox_password: "{  { netbox_password }}"
        netbox_validate_certs: "no"
  - name: vCenter Credentials
    kind: cloud
    inputs:
      fields:
        - id: vcenter_hostname
          type: string
          label: vCenter Hostname
        - id: vcenter_username
          type: string
          label: vCenter Username
        - id: vcenter_password
          type: string
          label: vCenter Password
          secret: yes
        - id: vcenter_datacenter
          type: string
          label: vCenter Datacenter
        - id: vcenter_cluster
          type: string
          label: vCenter Cluster
    injectors:
      extra_vars:
        vcenter_hostname: "{  { vcenter_hostname }}"
        vcenter_username: "{  { vcenter_username }}"
        vcenter_password: "{  { vcenter_password }}"
        vcenter_validate_certs: "no"
        vcenter_datacenter: "{  { vcenter_datacenter }}"
        vcenter_cluster: "{  { vcenter_cluster }}"
  - name: IDM Credentials
    kind: cloud
    inputs:
      fields:
        - id: idm_host
          type: string
          label: IDM Host
        - id: idm_password
          type: string
          label: IDM Password
          secret: yes
    injectors:
      extra_vars:
        idm_host: "{  { idm_host }}"
        idm_password: "{  { idm_password }}"
        idm_validate_certs: "no"
  - name: Satellite Credentials
    kind: cloud
    inputs:
      fields:
        - id: satellite_url
          type: string
          label: Satellite URL
        - id: satellite_username
          type: string
          label: Satellite Username
        - id: satellite_password
          type: string
          label: Satellite Password
          secret: yes
        - id: satellite_organization
          type: string
          label: Satellite Organization
        - id: satellite_location
          type: string
          label: Satellite Location
    injectors:
      extra_vars:
        satellite_url: "https://{  { audience | lower }}-{  { demo }}-satellite.{  { demo_uuid }}.{  { base_dns_suffix }}"
        satellite_username: "{  { satellite_username }}"
        satellite_password: "{  { satellite_password }}"
        satellite_validate_certs: "no"
        satellite_organization: "{  { audience }}"
        satellite_location: "{  { audience }}"
      env:
        XDG_CACHE_HOME: /tmp/.cache

controller_credentials:
  - name: Ansible Controller Credentials
    organization: "{  { audience }}"
    credential_type: Ansible Controller Credentials
  - name: Netbox Credentials
    organization: "{  { audience }}"
    credential_type: Netbox Credentials
  - name: vCenter Credentials
    organization: "{  { audience }}"
    credential_type: vCenter Credentials
  - name: IDM Credentials
    organization: "{  { audience }}"
    credential_type: IDM Credentials
  - name: Satellite Credentials
    organization: "{  { audience }}"
    credential_type: Satellite Credentials
  - name: Automation Hub Image Registry Credentials
    organization: "{  { audience }}"
    credential_type: Container Registry
    inputs:
      host: hub.lab.msp.redhat.com
      username: "{  { admin_username }}"
      password: "{  { admin_password }}"
      verify_ssl: no
  - name: Root Credentials
    credential_type: Machine
    organization: "{  { audience }}"
    inputs:
      username: root
      password: "{  { admin_password }}"

controller_execution_environments:
  - name: Josh's Demos Collection EE
    image: 'hub.lab.msp.redhat.com/joshs-demos-collection-ee:latest'
    organization: "{  { audience }}"
    credential: Automation Hub Image Registry Credentials
    pull: always

# controller_teams:
#   - name: "{  { audience }} SAP Infrastructure Team"
#     description: infrastructure team
#     organization: "{  { audience }}"
#   - name: "{  { audience }} BASIS Team"
#     description: BASIS team
#     organization: "{  { audience }}"
#   - name: "{  { audience }} Business Analyst Team"
#     description: BASIS team
#     organization: "{  { audience }}"

# controller_user_accounts:
#   - username: "{  { audience }}_admin"
#     password: "{{ admin_password }}"
#     email: dont@email.me
#     update_secrets: no
#   - username: "{  { audience }}_infrastructure"
#     password: "{{ admin_password }}"
#     email: dont@email.me
#     update_secrets: no
#   - username: "{  { audience }}_basis"
#     password: "{{ admin_password }}"
#     email: dont@email.me
#     update_secrets: no
#   - username: "{  { audience }}_business_analyst"
#     password: "{{ admin_password }}"
#     email: dont@email.me
#     update_secrets: no

controller_inventories:
  - name: "{  { audience }} Infrastructure"
    organization: "{  { audience }}"
    variables:
      company: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
      base_dns_suffix: "{  { base_dns_suffix }}"
      network_prefix: 10.15.120.0/22
      config_files:
        - hosts
        - resolv.conf
      timesync_ntp_servers:
        - hostname: 0.rhel.pool.ntp.org
          iburst: yes
        - hostname: 1.rhel.pool.ntp.org
          iburst: yes
        - hostname: 2.rhel.pool.ntp.org
          iburst: yes
        - hostname: 3.rhel.pool.ntp.org
          iburst: yes
      selinux_policy: targeted
      selinux_state: permissive
      dns_resolv:
        search_domains:
          - "{  { demo_uuid }}.{  { base_dns_suffix }}"
          - lab.msp.redhat.com
        nameservers:
          - 10.15.108.102
          - 10.15.108.101
        options:
          - 'timeout:1'
      base_packages:
        disable_gpg_check: yes
        packages:
          - lsof
          - vim
          - sos
          - redhat-support-tool
          - open-vm-tools
      ignore_virtual_disk_errors: yes
      remove_cdrom: no

controller_hosts:
  - name: localhost
    inventory: "{  { audience }} Infrastructure"
    variables:
      ansible_connection: local

controller_group_tiers: 1
controller_groups_tier1:
  - name: production
    inventory: "{  { audience }} Infrastructure"
    variables:
      lifecycle_environment: production


controller_projects:
  - name: Automation Utilities
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/jdc.git
  - name: Network Automation | IP Address Management
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: "https://{  { audience | lower }}-gitlab.{  { demo_uuid }}.{  { base_dns_suffix }}/network_automation/ip_address_management.git"
  - name: CMDB Automation | Record Management
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: "https://{  { audience | lower }}-gitlab.{  { demo_uuid }}.{  { base_dns_suffix }}/cmdb_automation/manage_records.git"
  - name: Network Automation | DNS Record Management
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: "https://{  { audience | lower }}-gitlab.{  { demo_uuid }}.{  { base_dns_suffix }}/network_automation/manage_dns_records.git"

controller_templates:
  - name: Get Available IP Address
    organization: "{  { audience }}"
    inventory: Demo Inventory
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Network Automation | IP Address Management
    playbook: playbooks/assign-ip-address.yml
    execution_environment: "{  { controller_execution_environments[0].name }}"
  - name: Update CMDB Records
    organization: "{  { audience }}"
    inventory: Demo Inventory
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: CMDB Automation | Record Management
    playbook: playbooks/manage-cmdb-records.yml
    execution_environment: "{  { controller_execution_environments[0].name }}"
  - name: Create DNS Records
    organization: "{  { audience }}"
    inventory: Demo Inventory
    ask_inventory_on_launch: yes
    ask_limit_on_launch: yes
    project: Network Automation | DNS Record Management
    playbook: playbooks/create-dns-records.yml
    execution_environment: "{  { controller_execution_environments[0].name }}"
  - name: Send Provisioner Email
    organization: "{{ controller_organization }}"
    inventory: Demo Inventory
    limit: localhost
    project: Automation Utilities
    allow_simultaneous: yes
    playbook: playbooks/send-email.yml
    execution_environment: "{  { controller_execution_environments[0].name }}"
    ask_variables_on_launch: yes

controller_workflows:
  - name: Provision Infrastructure
    organization: "{  { audience }}"
    state: "{{ controller_state | default('present') }}"
    inventory: "{  { audience }} Infrastructure"
    extra_vars:
      company: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
      base_dns_suffix: "{  { base_dns_suffix }}"
      provisioner: "{  { provisioner }}"
      provisioner_email: "{  { provisioner_email }}"
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: text
          question_name: "How Many Instnaces Should Be Provisioned?"
          variable: num_instances
          required: yes
          default: 1
        - type: multiplechoice
          question_name: "What Size Instances Are Required?"
          variable: demo
          choices:
            - small
            - medium
            - large
          required: yes
    simplified_workflow_nodes:
      - identifier: Get Available IP Address
        unified_job_template: Get Available IP Address
        limit: localhost
        success_nodes:
          - Update CMDB Records
        failure_nodes:
          - Send Failure Email About 'Get Available IP Address'
      - identifier: Send Failure Email About 'Get Available IP Address'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Get Available IP Address
      - identifier: Update CMDB Records
        unified_job_template: Update CMDB Records
        limit: localhost
        success_nodes:
          - Create DNS Records
        failure_nodes:
          - Send Failure Email About 'Update CMDB Records'
      - identifier: Send Failure Email About 'Update CMDB Records'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Update CMDB Records
      - identifier: Create DNS Records
        unified_job_template: Create DNS Records
        limit: localhost
        success_nodes:
          - Send Success Email
        failure_nodes:
          - Send Failure Email About 'Create DNS Records'
      - identifier: Send Failure Email About 'Create DNS Records'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Create DNS Records
      - identifier: Send Success Email
        unified_job_template: Send Provisioner Email
        extra_data:
          provisioner_status: success

# controller_roles:
#   # admin account
#   - user: "{  { audience }}_admin"
#     organization: "{  { audience }}"
#     role: admin
#   # Team Membership
#   - user: "{  { audience }}_infrastructure"
#     target_team: "{  { audience }} SAP Infrastructure Team"
#     organization: "{  { audience }}"
#     role: member
#   - user: "{  { audience }}_basis"
#     target_team: "{  { audience }} BASIS Team"
#     organization: "{  { audience }}"
#     role: member
#   - user: "{  { audience }}_business_analyst"
#     target_team: "{  { audience }} Business Analyst Team"
#     organization: "{  { audience }}"
#     role: member
  # # Infrastructure Permissions
  # - team: "{  { audience }} SAP Infrastructure Team"
  #   role: admin
  #   credentials:
  #     - Peripheral Credentials
  #     - Root Credentials
  # - team: "{  { audience }} Infrastructure Team"
  #   role: admin
  #   inventory: "{  { audience }} SAP Infrastructure"
  # - team: "{  { audience }} SAP Infrastructure Team"
  #   role: admin
  #   project: "{  { audience }} S4HANA Deployment Code"
  # - team: "{  { audience }} SAP Infrastructure Team"
  #   role: admin
  #   job_template: Add Hosts to Controller Inventory
  # - team: "{  { audience }} SAP Infrastructure Team"
  #   role: admin
  #   job_template: Provision Systems
  # # BASIS Permissions
  # - team: "{  { audience }} BASIS Team"
  #   role: read
  #   credentials:
  #     - Peripheral Credentials
  #     - Root Credentials
  # - team: "{  { audience }} BASIS Team"
  #   role: update
  #   inventory: "{  { audience }} SAP Infrastructure"
  # - team: "{  { audience }} BASIS Team"
  #   role: update
  #   project: "{  { audience }} S4HANA Deployment Code"
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Preconfigure for SAP
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Preconfigure for HANA
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Preconfigure for Netweaver
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Deploy SAP HANA
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Install Netweaver
  # - team: "{  { audience }} BASIS Team"
  #   role: admin
  #   job_template: Reinstate HSR
  # # Business Analyst Permissions
  # - team: "{  { audience }} Business Analyst Team"
  #   role: read
  #   credentials:
  #     - Peripheral Credentials
  #     - Root Credentials
  # - team: "{  { audience }} Business Analyst Team"
  #   role: read
  #   inventory: "{  { audience }} SAP Infrastructure"
  # - team: "{  { audience }} Business Analyst Team"
  #   role: read
  #   project: "{  { audience }} S4HANA Deployment Code"
  # - team: "{  { audience }} Business Analyst Team"
  #   role: execute
  #   workflow: Provision S4HANA SID