---

hub_install:
  admin_password: "{  { admin_password }}"
  pg:
    password: "{  { admin_password }}"

ah_host: "{  { inventory_hostname }}"
ah_username: "{  { admin_username }}"
ah_password: "{  { admin_password }}"
ah_validate_certs: no

ah_groups:
  - name: WebApp Automation Team
  - name: Network Automation Team
  - name: Virtualization Automation Team
  - name: Security Automation Team
  - name: Storage Automation Team
  - name: RHEL Automation Team
  - name: Automation Architecture Team

ah_users:
  - username: webapp_automation_admin
    groups:
      - WebApp Automation Team
    first_name: WebApp
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: network_automation_admin
    groups:
      - Network Automation Team
    first_name: Network
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: virtualization_automation_admin
    groups:
      - Virtualization Automation Team
    first_name: Virtualization
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: security_automation_admin
    groups:
      - Security Automation Team
    first_name: Security
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: storage_automation_admin
    groups:
      - Storage Automation Team
    first_name: Storage
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: rhel_automation_admin
    groups:
      - RHEL Automation Team
    first_name: WebApp
    last_name: Automation
    email: dont@email.me
    password: "{  { admin_password }}"
  - username: automation_admin
    groups:
      - Automation Architecture Team
    first_name: Automation
    last_name: Architecture
    email: dont@email.me
    password: "{  { admin_password }}"
    is_superuser: yes

ah_namespaces:
  - name: network_automation
    company: "{  { audience }}"
    email: "network-automation@{  { audience | lower }}.com"
    avatar_url: http://satellite.lab.msp.redhat.com/pub/network-switch.png
    description: "{  { audience }} Network Automation"
    resources: |
      # Redhat
      test namespace
    links:
      - name: "New_Google"
        url: "http://www.google.com"
    groups:
      - name: Network Automation Team
        object_permissions:
          - "change_namespace"
          - "upload_to_namespace"

ah_collections:
  - name: ip_address_management
    namespace: network_automation
    path: "files/{  { demo }}/network_automation-ip_address_management-1.0.0.tar.gz"