---

cpus: 4
memory_mb: 16384
os: rhel8
application: general

aap_download_url: http://satellite.lab.msp.redhat.com/pub/ansible-automation-platform-setup-2.1.2-1.tar.gz
aap_bundle: ansible-automation-platform-setup-2.1.2-1.tar.gz

controller_install:
  admin_password: "{  { admin_password }}"
  pg:
    password: "{  { admin_password }}"

bootstrap_controller: yes

controller_hostname: "{  { inventory_hostname }}"
controller_username: "{  { admin_username }}"
controller_password: "{  { admin_password }}"
controller_validate_certs: no

controller_license:
  manifest: /tmp/controller-manifest.zip

controller_organizations:
  - name: "{  { audience }}"

controller_credential_types:
  - name: Red Hat Registry Credentials
    kind: cloud
    injectors:
      extra_vars:
        redhat_registry_username: "{  { redhat_registry_username }}"
        redhat_registry_password: "{  { redhat_registry_password }}"
  - name: RHC Edge Credentials
    kind: cloud
    injectors:
      extra_vars:
        rhc_org_id: "{  { rhc_org_id }}"
        rhc_activation_key: "{  { rhc_activation_key }}" 
  - name: Controller API Credentials
    kind: cloud
    injectors:
      extra_vars:
        controller_hostname: "https://{  { audience | lower }}-{  { demo }}-controller.{  { demo_uuid }}.{  { base_dns_suffix }}"
        controller_username: "{  { controller_username }}"
        controller_password: "{  { controller_password }}"
  - name: vCenter Credentials
    kind: cloud
    injectors:
      extra_vars:
        vcenter_hostname: "{  { vcenter_hostname }}"
        vcenter_username: "{  { vcenter_username }}"
        vcenter_password: "{  { vcenter_password }}"
        vcenter_validate_certs: "no"
        vcenter_datacenter: "{  { vcenter_datacenter }}"
        vcenter_cluster: "{  { vcenter_cluster }}"
        vcenter_datastore: storage04-nfs-lun00

controller_credentials:
  - name: Automation Hub Image Registry Credentials
    organization: "{  { audience }}"
    credential_type: Container Registry
    inputs:
      host: hub.lab.msp.redhat.com
      username: "{  { admin_username }}"
      password: "{  { admin_password }}"
      verify_ssl: no
  - name: Red Hat Registry Credentials
    organization: "{  { audience }}"
    credential_type: Red Hat Registry Credentials
  - name: Root Credentials
    organization: "{  { audience }}"
    credential_type: Machine
    username: root
    password: "{  { admin_password }}"
  - name: RHC Edge Credentials
    credential_type: RHC Edge Credentials
    organization: "{  { audience }}"
  - name: Controller API Credentials
    organization: "{  { audience }}"
    credential_type: Controller API Credentials
  - name: vCenter Credentials
    organization: "{  { audience }}"
    credential_type: vCenter Credentials

controller_execution_environments:
  - name: Josh's Demos Collection EE
    image: 'hub.lab.msp.redhat.com/joshs-demos-collection-ee:latest'
    organization: "{  { audience }}"
    credential: Automation Hub Image Registry Credentials
    pull: always

controller_inventories:
  - name: "{  { audience }} Edge Systems"
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
  - name: "{  { audience }} Edge Utilities"
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
  - name: Local Actions
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
      base_dns_suffix: "{  { base_dns_suffix }}"

controller_hosts:
  - name: "pos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "bos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "bos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "bos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "bos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pc1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pc2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "po1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "po2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pc1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "pc2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "po1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "po2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Systems"
  - name: "edge-utilities.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Utilities"
  - name: localhost
    inventory: Local Actions
    variables:
      ansible_connection: local
      ansible_python_interpreter: "{  { ansible_playbook_python }}"

controller_group_tiers: 2

controller_groups_tier1:
  - name: point_of_sale
    inventory: "{  { audience }} Edge Systems"
    variables:
      sys_purpose: point-of-sale
    hosts:
      - "pos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: back_of_store
    inventory: "{  { audience }} Edge Systems"
    variables:
      sys_purpose: back-of-store
    hosts:
      - "bos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: process_control
    inventory: "{  { audience }} Edge Systems"
    variables:
      sys_purpose: process-control
    hosts:
      - "pc1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pc2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pc1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pc2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: plant_operations
    inventory: "{  { audience }} Edge Systems"
    variables:
      sys_purpose: process-control
    hosts:
      - "po1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: store1000
    inventory: "{  { audience }} Edge Systems"
    variables:
      country: US
      state: MN
      City: Saint Paul
    hosts:
      - "pos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos1-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos2-store1000.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: store1001
    inventory: "{  { audience }} Edge Systems"
    variables:
      country: US
      state: WI
      City: Milwaukee
    hosts:
      - "pos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos1-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "bos2-store1001.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: plant100
    inventory: "{  { audience }} Edge Systems"
    variables:
      country: US
      state: IN
      City: Lafayette
    hosts:
      - "pc1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pc2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po1-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po2-mfgplant100.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: plant101
    inventory: "{  { audience }} Edge Systems"
    variables:
      country: US
      state: IN
      City: West Lafayette
    hosts:
      - "pc1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "pc2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po1-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "po2-mfgplant101.{{ demo_uuid }}.{{ base_dns_suffix }}"

controller_groups_tier2:
  - name: retail_stores
    inventory: "{  { audience }} Edge Systems"
    children:
      - store1000
      - store1001
  - name: manufacturing_plants
    inventory: "{  { audience }} Edge Systems"
    children:
      - plant100
      - plant101

controller_projects:
  - name: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/jdc.git

controller_templates:
  - name: Create Edge Installer ISO
    inventory: "{  { audience }} Edge Utilities"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/create-edge-installer-iso.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - Root Credentials
      - RHC Edge Credentials
      - Controller API Credentials
      - Red Hat Registry Credentials
      - vCenter Credentials
  - name: Provision Edge Systems
    inventory: Local Actions
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/provision-rhel-edge-system.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - vCenter Credentials

# controller_workflows:
#   - name: Pre-Patching | Non_Production | Security
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Run Insights Report | Non_Production | Security'
#         identifier: Approve 'Run Insights Report | Non_Production | Security'
#         success_nodes:
#           - Run Insights Report | Non_Production | Security
#       - unified_job_template: Run Insights Report | Non_Production | Security
#         identifier: Run Insights Report | Non_Production | Security
#       - approval_node:
#           name: Approve 'Check for Updates | Non_Production | Security'
#         identifier: Approve 'Check for Updates | Non_Production | Security'
#         success_nodes:
#           - Check for Updates | Non_Production | Security
#       - unified_job_template: Check for Updates | Non_Production | Security
#         identifier: Check for Updates | Non_Production | Security
#   - name: Pre-Patching | Non_Production | Infrastructure
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Install Tracer | Non_Production | Infrastructure'
#         identifier: Approve 'Install Tracer | Non_Production | Infrastructure'
#         success_nodes:
#           - Install Tracer | Non_Production | Infrastructure
#       - unified_job_template: Install Tracer | Non_Production | Infrastructure
#         identifier: Install Tracer | Non_Production | Infrastructure
#   - name: Pre-Patching | Non_Production | BASIS (Application Team)
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Standby Secondary Database | Non_Production | BASIS (Application Team)'
#         identifier: Approve 'Standby Secondary Database | Non_Production | BASIS (Application Team)'
#         success_nodes:
#           - Standby Secondary Database | Non_Production | BASIS (Application Team)
#       - unified_job_template: Standby Secondary Database | Non_Production | BASIS (Application Team)
#         identifier: Standby Secondary Database | Non_Production | BASIS (Application Team)
#   - name: Patching | Non_Production | Infrastructure
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Update All Packages | Non_Production | Infrastructure'
#         identifier: Approve 'Update All Packages | Non_Production | Infrastructure'
#         success_nodes:
#           - Update All Packages | Non_Production | Infrastructure
#       - unified_job_template: Update All Packages | Non_Production | Infrastructure
#         identifier: Update All Packages | Non_Production | Infrastructure
#         success_nodes:
#           - Approve 'Run Tracer Report | Non_Production | Infrastructure'
#       - approval_node:
#           name: Approve 'Run Tracer Report | Non_Production | Infrastructure'
#         identifier: Approve 'Run Tracer Report | Non_Production | Infrastructure'
#         success_nodes:
#           - Run Tracer Report | Non_Production | Infrastructure
#       - unified_job_template: Run Tracer Report | Non_Production | Infrastructure
#         identifier: Run Tracer Report | Non_Production | Infrastructure
#         success_nodes:
#           - Approve 'Reboot Server | Non_Production | Infrastructure'
#       - approval_node:
#           name: Approve 'Reboot Server | Non_Production | Infrastructure'
#         identifier: Approve 'Reboot Server | Non_Production | Infrastructure'
#         success_nodes:
#           - Reboot Server | Non_Production | Infrastructure
#       - unified_job_template: Reboot Server | Non_Production | Infrastructure
#         identifier: Reboot Server | Non_Production | Infrastructure
#       - approval_node:
#           name: Approve 'Kpatch Server | Non_Production | Infrastructure'
#         identifier: Approve 'Kpatch Server | Non_Production | Infrastructure'
#         success_nodes:
#           - Kpatch Server | Non_Production | Infrastructure
#       - unified_job_template: Kpatch Server | Non_Production | Infrastructure
#         identifier: Kpatch Server | Non_Production | Infrastructure
#   - name: Post-Patching | Non_Production | Security
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Run Insights Report | Non_Production | Security'
#         identifier: Approve 'Run Insights Report | Non_Production | Security'
#         success_nodes:
#           - Run Insights Report | Non_Production | Security
#       - unified_job_template: Run Insights Report | Non_Production | Security
#         identifier: Run Insights Report | Non_Production | Security
#       - approval_node:
#           name: Approve 'Check for Updates | Non_Production | Security'
#         identifier: Approve 'Check for Updates | Non_Production | Security'
#         success_nodes:
#           - Check for Updates | Non_Production | Security
#       - unified_job_template: Check for Updates | Non_Production | Security
#         identifier: Check for Updates | Non_Production | Security
#   - name: Post-Patching | Non_Production | BASIS (Application Team)
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - approval_node:
#           name: Approve 'Unstandby Secondary Database | Non_Production | BASIS (Application Team)'
#         identifier: Approve 'Unstandby Secondary Database | Non_Production | BASIS (Application Team)'
#         success_nodes:
#           - Unstandby Secondary Database | Non_Production | BASIS (Application Team)
#       - unified_job_template: Unstandby Secondary Database | Non_Production | BASIS (Application Team)
#         identifier: Unstandby Secondary Database | Non_Production | BASIS (Application Team)
#   - name: Patch Non_Production
#     organization: "{  { audience }}"
#     state: "{{ controller_state | default('present') }}"
#     simplified_workflow_nodes:
#       - unified_job_template: Pre-Patching | Non_Production | Security
#         identifier: Pre-Patching | Non_Production | Security
#         success_nodes:
#           - Pre-Patching | Non_Production | Infrastructure
#       - unified_job_template: Pre-Patching | Non_Production | Infrastructure
#         identifier: Pre-Patching | Non_Production | Infrastructure
#         success_nodes:
#           - Pre-Patching | Non_Production | BASIS (Application Team)
#       - unified_job_template: Pre-Patching | Non_Production | BASIS (Application Team)
#         identifier: Pre-Patching | Non_Production | BASIS (Application Team)
#         success_nodes:
#           - Patching | Non_Production | Infrastructure
#       - unified_job_template: Patching | Non_Production | Infrastructure
#         identifier: Patching | Non_Production | Infrastructure
#         success_nodes:
#           - Post-Patching | Non_Production | Security
#       - unified_job_template: Post-Patching | Non_Production | Security
#         identifier: Post-Patching | Non_Production | Security
#         success_nodes:
#           - Post-Patching | Non_Production | BASIS (Application Team)
#       - unified_job_template: Post-Patching | Non_Production | BASIS (Application Team)
#         identifier: Post-Patching | Non_Production | BASIS (Application Team)
#         success_nodes:
#           - Approve 'Promote Content to Production | Infrastructure'
#       - approval_node:
#           name: Approve 'Promote Content to Production | Infrastructure'
#         identifier: Approve 'Promote Content to Production | Infrastructure'
#         success_nodes:
#           - Promote Content to Production | Infrastructure
#       - unified_job_template: Promote Content to Production | Infrastructure
#         identifier: Promote Content to Production | Infrastructure
