---

cpus: 4
memory_mb: 16384
os: rhel8
application: general

aap_download_url: http://satellite.lab.msp.redhat.com/pub/ansible-automation-platform-setup-latest.tar.gz
aap_installer_bundle: ansible-automation-platform-setup-latest.tar.gz

controller_install:
  admin_password: "{  { admin_password }}"
  pg:
    password: "{  { admin_password }}"

bootstrap_controller: yes

controller_hostname: "{  { inventory_hostname }}"
controller_username: "{  { admin_username }}"
controller_password: "{  { admin_password }}"
controller_validate_certs: no

controller_configuration_projects_async_retries: 60
controller_configuration_projects_async_delay: 5

controller_license:
  manifest: /tmp/controller-manifest.zip

controller_organizations:
  - name: "{  { audience }}"

controller_credential_types:
  - name: Red Hat Registry Credentials
    kind: cloud
    injectors:
      extra_vars:
        redhat_registry_username: "{  { redhat_registry_username }}"
        redhat_registry_password: "{  { redhat_registry_password }}"
  - name: RHC Edge Credentials
    kind: cloud
    injectors:
      extra_vars:
        rhc_org_id: "{  { rhc_org_id }}"
        rhc_activation_key: "{  { rhc_activation_key }}" 
  - name: Controller API Credentials
    kind: cloud
    injectors:
      extra_vars:
        controller_hostname: "{  { audience | lower }}-{  { demo }}-controller.{  { demo_uuid }}.{  { base_dns_suffix }}"
        controller_username: "{  { controller_username }}"
        controller_password: "{  { controller_password }}"
        controller_validate_certs: 'no'
  - name: vCenter Credentials
    kind: cloud
    injectors:
      extra_vars:
        vcenter_hostname: "{  { vcenter_hostname }}"
        vcenter_username: "{  { vcenter_username }}"
        vcenter_password: "{  { vcenter_password }}"
        vcenter_validate_certs: "no"
        vcenter_datacenter: "{  { vcenter_datacenter }}"
        vcenter_cluster: "{  { vcenter_cluster }}"
        vcenter_datastore: storage04-nfs-lun0
  - name: Console Dot Offline Token
    kind: cloud
    injectors:
      extra_vars:
        console_dot_offline_token: "{  { console_dot_offline_token }}"
  - name: Edge Workload Image Registry Credentials
    kind: cloud
    injectors:
      extra_vars:
        edge_workload_registry_username: "{  { admin_username }}"
        edge_workload_registry_password: "{  { admin_password }}"
  - name: Automation Hub Image Registry Credentials
    kind: cloud
    injectors:
      extra_vars:
        hub_image_registry_username: "{  { admin_username }}"
        hub_image_registry_password: "{  { admin_password }}"
        hub_image_registry_tls_verify: 'no'
          

controller_credentials:
  - name: Automation Hub Image Registry Credentials
    organization: "{  { audience }}"
    credential_type: Container Registry
    inputs:
      host: hub.lab.msp.redhat.com
      username: "{  { admin_username }}"
      password: "{  { admin_password }}"
      verify_ssl: no
  - name: Red Hat Registry Credentials
    organization: "{  { audience }}"
    credential_type: Red Hat Registry Credentials
  - name: Root Credentials
    organization: "{  { audience }}"
    credential_type: Machine
    inputs:
      username: root
      password: "{  { admin_password }}"
  - name: RHC Edge Credentials
    credential_type: RHC Edge Credentials
    organization: "{  { audience }}"
  - name: Controller API Credentials
    organization: "{  { audience }}"
    credential_type: Controller API Credentials
  - name: vCenter Credentials
    organization: "{  { audience }}"
    credential_type: vCenter Credentials
  - name: Edge User Credentials
    organization: "{  { audience }}"
    credential_type: Machine
    inputs:
      username: "{  { edge_user_username }}"
      ssh_key_data: "{  { edge_user_ssh_key_data }}"
  - name: Console Dot Offline Token
    organization: "{  { audience }}"
    credential_type: Console Dot Offline Token
  - name: Local Automation Hub Image Registry Credentials
    organization: "{  { audience }}"
    credential_type: Automation Hub Image Registry Credentials


controller_execution_environments:
  - name: Josh's Demos Collection EE
    image: 'hub.lab.msp.redhat.com/joshs-demos-collection-ee:latest'
    organization: "{  { audience }}"
    credential: Automation Hub Image Registry Credentials
    pull: always

controller_inventories:
  - name: "{  { audience }} Edge Systems"
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
  - name: "{  { audience }} Edge Utilities"
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
  - name: Local Actions
    organization: "{  { audience }}"
    variables:
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"
      base_dns_suffix: "{  { base_dns_suffix }}"

controller_hosts:
  - name: "edge-utilities.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "{  { audience }} Edge Utilities"
    variables:
      edge_workload_info:
        image_registry: "{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}"
        pod:
          name: process-control-demo
          ports:
            - 1881:1881
        containers:
          - name: mqtt
            src: https://github.com/jjaswanson4/process-demo-mqtt.git
            image: "{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}/mqtt:latest"
          - name: control
            src: https://github.com/jjaswanson4/process-demo-control.git
            image: "{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}/control:latest"
          - name: simulate
            src: https://github.com/jjaswanson4/process-demo-simulate.git
            image: "{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}/simulate:latest"
          - name: ui
            src: https://github.com/jjaswanson4/process-demo-ui.git
            image: "{  { audience | lower }}-{  { demo }}-hub.{  { demo_uuid }}.{  { base_dns_suffix }}/ui:latest"

  - name: localhost
    inventory: Local Actions
    variables:
      ansible_connection: local
      ansible_python_interpreter: "{  { ansible_playbook_python }}"
      audience: "{  { audience }}"
      demo_uuid: "{  { demo_uuid }}"

controller_group_tiers: 0

controller_projects:
  - name: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/jdc.git

controller_templates:
  - name: Create Edge Installer ISO
    inventory: "{  { audience }} Edge Utilities"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/create-edge-installer-iso.yml
    execution_environment: Josh's Demos Collection EE
    ask_variables_on_launch: yes
    allow_simultaneous: yes
    credentials:
      - Root Credentials
      - RHC Edge Credentials
      - Controller API Credentials
      - Red Hat Registry Credentials
      - vCenter Credentials
  - name: Provision Edge Systems
    inventory: Local Actions
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/provision-rhel-edge-system.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - vCenter Credentials
  - name: Apply Configuration to Edge Device
    inventory: "{  { audience }} Edge Systems"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/post-install-rhel-edge-systems.yml
    execution_environment: Josh's Demos Collection EE
    ask_limit_on_launch: yes
    become_enabled: yes
    allow_simultaneous: yes
    credentials:
      - Edge User Credentials
  - name: Add Device to Edge Management Group
    inventory: "{  { audience }} Edge Systems"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/add-device-to-group-in-edge-mgmt.yml
    execution_environment: Josh's Demos Collection EE
    ask_limit_on_launch: yes
    become_enabled: yes
    allow_simultaneous: yes
    credentials:
      - Console Dot Offline Token
  - name: Create Edge Devices Inventory
    inventory: Local Actions
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/create-edge-inventory-in-controller.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - Controller API Credentials
  - name: Build Edge Workload
    inventory: "{  { audience }} Edge Utilities"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/build-edge-workload.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - Root Credentials
      - Red Hat Registry Credentials
      - Local Automation Hub Image Registry Credentials
  - name: Add Edge Device to Controller Group
    inventory: "{  { audience }} Edge Utilities"
    project: "{  { audience }} Edge Management Codebase"
    organization: "{  { audience }}"
    playbook: playbooks/add-edge-device-to-controller-group.yml
    execution_environment: Josh's Demos Collection EE
    credentials:
      - Edge User Credentials
      - Controller API Credentials

controller_workflows:
  - name: Deploy Edge Systems
    organization: "{  { audience }}"
    state: present
    extra_vars:
      audience: "{  { audience }}"
      demo: "{  { demo }}"
      demo_uuid: "{  { demo_uuid }}"
      base_dns_suffix: "{{ base_dns_suffix }}"
    survey_enabled: yes
    survey:
      name: ''
      description: ''
      spec:
        - type: multiplechoice
          question_name: Workload Type?
          question_description: What workload should be run?
          variable: edge_workload
          choices:
            - Process Control
            - In-Store Display
          required: yes
          default: Process Control
        - type: text
          question_name: In-Store Display Website?
          question_description: If building in-store displays, what website should they display?
          variable: display_website
          required: no
          default: "https://{  { audience | lower }}.com"
    simplified_workflow_nodes:
      - identifier: Create Human Machine Interface Installer ISO
        unified_job_template: Create Edge Installer ISO
        extra_data:
          source_installer_image: rhel-edge-hmi-image.iso
        success_nodes:
          - Provision Edge Systems
      - identifier: Create Process Control System Installer ISO
        unified_job_template: Create Edge Installer ISO
        extra_data:
          source_installer_image: rhel-edge-pcs-image.iso
        success_nodes:
          - Provision Edge Systems
      - identifier: Create Edge Devices Inventory
        unified_job_template: Create Edge Devices Inventory
        success_nodes:
          - Provision Edge Systems
      - identifier: Build Edge Workload
        unified_job_template: Build Edge Workload
        success_nodes:
          - Provision Edge Systems
      - identifier: Provision Edge Systems
        unified_job_template: Provision Edge Systems
        all_parents_must_converge: yes

        
  - name: Post-Install Edge System
    organization: "{  { audience }}"
    state: present
    ask_limit_on_launch: yes
    allow_simultaneous: yes
    simplified_workflow_nodes:
      - identifier: Apply Configuration to Edge Device
        unified_job_template: Apply Configuration to Edge Device
        success_nodes:
          - Add Edge Device to Controller Group
      - identifier: Add Edge Device to Controller Group
        unified_job_template: Add Edge Device to Controller Group
        # success_nodes:
        #   - Add Edge Device to Controller Group   
      # - identifier: Add Device to Edge Management Group
      #   unified_job_template: Add Device to Edge Management Group