---

- name: run tasks from {{ delegate_host }}
  block:
    - name: get auth token for netbox
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/users/tokens/provision/"
        validate_certs: "{{ netbox_validate_certs | default(omit) }}"
        method: POST
        status_code: 201
        body_format: json
        body:
          username: "{{ netbox_username }}"
          password: "{{ netbox_password }}"
      register: netbox_auth_token_raw
      throttle: 5
    - name: set netbox token fact
      ansible.builtin.set_fact:
        netbox_token: "{{ netbox_auth_token_raw.json.key }}"
  delegate_to: "{{ delegate_host }}"

- import_tasks: get-allocated-ip-addresses.yml

- import_tasks: manage-dns-records.yml

- name: include tasks for VIPs
  ansible.builtin.include_tasks:
    file: "{{ task_file }}"
  loop_control:
    loop_var: task_file
  loop:
    - get-vip-ip-addresses.yml
    - manage-vip-records.yml
  when:
    - virtual_ip is defined