---

- name: run tasks from "{{ delegate_host }}"
  block:
    - name: manage A records
      community.general.ipa_dnsrecord:
        ipa_host: "{{ idm_host }}"
        ipa_pass: "{{ idm_password }}"
        validate_certs: "{{ idm_validate_certs | default(false) }}"
        zone_name: "{{ demo_uuid }}.{{ base_dns_suffix }}"
        record_name: "{{ virtual_ip.dns_record.split('.')[0] }}"
        record_value: "{{ ip_address }}"
        record_type: A
        state: "{{ dns_records_state | default(omit) }}"
    - name: manage PTR records
      community.general.ipa_dnsrecord:
        ipa_host: "{{ idm_host }}"
        ipa_pass: "{{ idm_password }}"
        validate_certs: "{{ idm_validate_certs | default(false) }}"
        zone_name: "{{ vip_address.split('.')[2] }}.{{ vip_address.split('.')[1] }}.{{ vip_address.split('.')[0] }}.in-addr.arpa."
        record_name: "{{ vip_address.split('.')[-1] }}"
        record_value: "{{ virtual_ip.dns_record }}."
        record_type: PTR
        state: "{{ dns_records_state | default(omit) }}"
  throttle: 1
  delegate_to: "{{ delegate_host }}"