---

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: import tasks to pull container images
  ansible.builtin.import_tasks: pull-images.yml

- name: import tasks to setup pod
  ansible.builtin.import_tasks: setup-pod.yml

- name: import tasks to setup containers
  ansible.builtin.import_tasks: setup-containers.yml

- name: import tasks to ensure workload is started/monitored
  ansible.builtin.import_tasks: setup-systemd.yml

- name: import tasks to configure the system firewall
  ansible.builtin.import_tasks: configure-firewall.yml
