---

- name: deploy containerized workload to edge device
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    state: present
    generate_systemd:
      path: /tmp
      restart_policy: always
      names: true
  loop_control:
    loop_var: container
  loop: "{{ edge_workload_info.containers }}"

- name: ensure port 8080 is allowed through the firewall
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true