---

- name: create pod for containers
  containers.podman.podman_pod:
    name: "{{ edge_workload_info.pod.name }}"
    ports: "{{ edge_workload_info.pod.ports }}"
    generate_systemd:
      path: /tmp

- name: gather up service files
  ansible.builtin.find:
    paths: /tmp
    patterns: '*service'
  register: service_files

- debug:
    msg: "{{ service_files }}"

- name: copy generated systemd file to systemd dir
  ansible.builtin.copy:
    src: "{{ file.path }}"
    dest: /etc/systemd/user/
    remote_src: yes
  loop_control:
    loop_var: file
  loop: "{{ service_files.files }}"
  become: true

# - name: reload systemd
#   ansible.builtin.systemd:
#     daemon_reload: yes
#     scope: user

# - name: ensure systemd watches containers and pod
#   ansible.builtin.systemd:
#     name: "{{ file."
#     state: started
#     scope: user
#     enabled: yes
#   loop_control:
#     loop_var: file
#   loop: "{{ service_files.files }}"
#   become: true