---

- name: deploy containerized workload to edge device
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    pod: "{{ edge_workload.pod.name }}"
    state: present
    generate_systemd:
      path: /tmp
      restart_policy: always
      names: true
  loop_control:
    loop_var: container
  loop: "{{ edge_workload_info.containers }}"

