---

# By default, the org 'Demo Provisioner' is created and resources are configured there,
# Use this variable to override this behavior.
# For example, overriding to 'Default' will put the resources into the default controller organization.
controller_organization: Demo Provisioner

# This is the default project name. It is a var so demos can import specific job templates and override the project locally.
# Change this to change the name of the project for the provisioner job templates.
project: Josh's Demos Collection

# This is the default prefix for assets created for this demo.
# Change this variable to use a different prefix.
demo_prefix: AAP Advanced Automation

# This is the realitive path to the vars files for this demo.
# Typically this contains a vars file for the provisioner, Satellite, and Controller.
vars_files_path: "vars/demos/{{ demo }}"

# This is the information used for the instance of Controller for the demo.
# This can be the same instance as where the provisioner is deployed, but it's not recommended.
controller_configuration_file: "{{ vars_files_path }}/controller.yml"

# This is the information used for the instance of Satellite for the demo.
# This can be the same instance as where the provisioner is deployed, but it's not recommended.
satellite_configuration_file: "{{ vars_files_path }}/satellite.yml"

base_dns_suffix: demos.lcl

# This toggles secure logging, for example: when configuring credentials on Ansible Controller.
# Since I'm using my own instance, secure logging isn't a requirement.
controller_configuration_credentials_secure_logging: no

# These are where demo specific components are defined, in hash form. These will automatically be added to the common resources.
# If there is no need for a specific, resource, simply define an empty var, such as `controller_organizations: []`
controller_organizations: []
controller_credential_types: []
controller_execution_environments: []
controller_inventories: []
controller_projects: []
controller_credentials: []
controller_templates: []

controller_configuration_projects_async_retries: 60
controller_configuration_projects_async_delay: 5

controller_hosts:
  - name: "database-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "control-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "control-node-3.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc1-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc2-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc2-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc2-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc2-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "azure-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "azure-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "azure-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "azure-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aws-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aws-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aws-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aws-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "mfgplant1-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "mfgplant1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "dc2-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "azure-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aws-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "mfgplant1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"
  - name: "aap-metrics.{{ demo_uuid }}.{{ base_dns_suffix }}"
    inventory: "Demo {{ demo_uuid }} Inventory"

controller_group_tiers: 3

controller_groups_tier1:
  - name: database_nodes
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "database-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: aap_installer_node
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "{{ audience | lower }}-{{ demo }}-controller.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: control_nodes
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "{{ audience | lower }}-{{ demo }}-controller.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "control-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "control-node-3.{{ demo_uuid }}.{{ base_dns_suffix }}"
    variables:
      node_type: control
  - name: execution_nodes
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "dc1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc1-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "mfgplant1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
    variables:
      node_type: execution
  - name: hop_nodes
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "dc2-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "mfgplant1-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: managed_endpoints
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "dc1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "mfgplant1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: azure
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "azure-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "azure-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: aws
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "aws-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "aws-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: dc1
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "dc1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc1-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: dc2
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "dc2-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-hop-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-execution-node-2.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "dc2-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: mfgplant1
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "mfgplant1-hop-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "mfgplant1-execution-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
      - "mfgplant1-managed-node-1.{{ demo_uuid }}.{{ base_dns_suffix }}"
  - name: metrics_collection
    inventory: "Demo {{ demo_uuid }} Inventory"
    hosts:
      - "aap-metrics.{{ demo_uuid }}.{{ base_dns_suffix }}"
    variables:
      cpus: 4
      memory_mb: 8192
      metrics_graph_service: yes
      metrics_query_service: yes
      metrics_rention_days: 14
      metrics_monitored_hosts:  "{  { groups['aap_infrastructure'] }}"

controller_groups_tier2:
  - name: aap_infrastructure
    inventory: "Demo {{ demo_uuid }} Inventory"
    children:
      - control_nodes
      - execution_nodes
      - hop_nodes
      - database_nodes
    variables:
      cpus: 4
      memory_mb: 16384
      aap_download_url: http://satellite.lab.msp.redhat.com/pub/ansible-automation-platform-setup-latest.tar.gz
      aap_installer_bundle: ansible-automation-platform-setup-latest.tar.gz
      controller_install:
        admin_password: "{  { admin_password }}"
        pg:
          password: "{  { admin_password }}"
      bootstrap_controller: yes
      controller_hostname: "{  { inventory_hostname }}"
      controller_username: "{  { admin_username }}"
      controller_password: "{  { admin_password }}"
      controller_validate_certs: no

controller_groups_tier3:
  - name: demo_hosts
    inventory: "Demo {{ demo_uuid }} Inventory"
    children:
      - aap_infrastructure
      - managed_endpoints
      - metrics_collection
    variables:
      htop_url: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm
      firewall:
        name: firewalld
        state: stopped
        enabled: no
      cpus: 2
      memory_mb: 4096
      os: rhel8
      application: general
      lifecycle_environment: production
      run_additional_roles: yes
      provisioning:
        host_group: "{  { os }}/vlan146"
        method: bootdisk
        dns_domain: "{  { demo_uuid }}.{  { base_dns_suffix }}"
        cpus: "{  { cpus }}"
        memory_mb: "{  { memory_mb }}"
        activation_keys: "ak-{  { application }}-{  { os }}-{  { lifecycle_environment }}"
      config_files:
        - hosts
        - resolv.conf
      timesync_ntp_servers:
        - hostname: 0.rhel.pool.ntp.org
          iburst: yes
        - hostname: 1.rhel.pool.ntp.org
          iburst: yes
        - hostname: 2.rhel.pool.ntp.org
          iburst: yes
        - hostname: 3.rhel.pool.ntp.org
          iburst: yes

controller_workflows:
  - name: Provision AAP Advanced Architecture Demo
    organization: Demo Provisioner
    state: "{{ controller_state | default('present') }}"
    ask_inventory_on_launch: yes
    ask_variables_on_launch: yes
    extra_vars:
      demo: aap-aa
    simplified_workflow_nodes:
      - identifier: Create CMDB Records
        unified_job_template: Manage CMDB Records
        limit: demo_hosts
        credentials:
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner vCenter Credentials
        success_nodes:
          - Create DNS Records
        failure_nodes:
          - Send Failure Email About 'Create CMDB Records'
      - identifier: Send Failure Email About 'Create CMDB Records'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Create CMDB Records
      - identifier: Create DNS Records
        unified_job_template: Manage DNS Records
        limit: demo_hosts
        credentials:
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner IDM Credentials
        success_nodes:
          - Provision Demo Systems
        failure_nodes:
          - Send Failure Email About 'Create DNS Records'
      - identifier: Send Failure Email About 'Create DNS Records'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Create DNS Records
      - identifier: Provision Demo Systems
        unified_job_template: Provision Systems
        limit: demo_hosts
        credentials:
          - Demo Provisioner vCenter Credentials
          - Demo Provisioner Admin Credentials
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner Root Account
          - Demo Provisioner Satellite Credentials
        success_nodes:
          - Apply Standard Config to Demo Hosts
        failure_nodes:
          - Send Failure Email About 'Provision Demo Systems'
      - identifier: Send Failure Email About 'Provision Demo Systems'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Provision Demo Systems
      - identifier: Apply Standard Config to Demo Hosts
        unified_job_template: Apply Standard Configuration
        limit: demo_hosts
        credentials:
          - Demo Provisioner Root Account
        success_nodes:
          - Install Ansible Automation Platform
        failure_nodes:
          - Send Failure Email About 'Apply Standard Config to Demo Hosts'
      - identifier: Send Failure Email About 'Apply Standard Config to Demo Hosts'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Apply Standard Config to Demo Hosts
      - identifier: Install Ansible Automation Platform
        unified_job_template: Install Ansible Controller
        limit: aap_installer_node
        credentials:
          - Demo Provisioner Red Hat Registry Credentials
          - Demo Provisioner Root Account
          - Demo Provisioner Admin Credentials
        extra_data:
          use_advanced_inventory: yes
        success_nodes:
          - Configure Ansible Controller
        failure_nodes:
          - Send Failure Email About 'Install Ansible Controller'
      - identifier: Send Failure Email About 'Install Ansible Controller'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Install Ansible Controller
      - identifier: Configure Ansible Controller
        unified_job_template: Configure Ansible Controller
        limit: aap_installer_node
        credentials:
          - Demo Provisioner Admin Credentials
        # success_nodes:
        #   - Send Success Email
        failure_nodes:
          - Send Failure Email About 'Configure Ansible Controller'
      - identifier: Send Failure Email About 'Configure Ansible Controller'
        unified_job_template: Send Provisioner Email
        extra_data:
          failed_at_step: Configure Ansible Controller

  - name: Teardown AAP Advanced Architecture Demo
    organization: Demo Provisioner
    ask_inventory_on_launch: yes
    ask_variables_on_launch: yes
    state: "{{ controller_state | default('present') }}"
    extra_vars:
      demo: aap-aa
    simplified_workflow_nodes:
      - identifier: Unregister from Insights
        unified_job_template: Unregister from Insights
        limit: demo_hosts
        credentials:
          - Demo Provisioner Root Account
          - Demo Provisioner Admin Credentials
        always_nodes:
          - Teardown Demo Hosts
      - identifier: Teardown Demo Hosts
        unified_job_template: Teardown Systems
        limit: demo_hosts
        credentials:
          - Demo Provisioner Root Account
          - Demo Provisioner Admin Credentials
          - Demo Provisioner Satellite Credentials
        always_nodes:
          - Cleanup DNS Records
      - identifier: Cleanup DNS Records
        unified_job_template: Manage DNS Records
        limit: demo_hosts
        credentials:
          - Demo Provisioner Admin Credentials
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner IDM Credentials
        extra_data:
          dns_records_state: absent
        always_nodes:
          - Remove CMDB Records
      - identifier: Remove CMDB Records
        unified_job_template: Manage CMDB Records
        limit: 'demo_hosts:management_plane'
        credentials:
          - Demo Provisioner Admin Credentials
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner vCenter Credentials
        extra_data:
          cmdb_record_state: absent
        always_nodes:
          - Remove Demo Context
      - identifier: Remove Demo Context
        unified_job_template: Configure Demo Context
        credentials:
          - Demo Provisioner Netbox Credentials
          - Demo Provisioner vCenter Credentials
          - Demo Provisioner IDM Credentials
          - Demo Provisioner Satellite Credentials
        extra_data:
          demo_context_state: absent
