---

- name: find the installer directory
  ansible.builtin.find:
    paths: /tmp/aap-installer/
    patterns: "ansible*"
    file_type: directory
  register: installer_directory

- name: push our version of the inventory file
  ansible.builtin.template:
    src: templates/inventory.j2
    dest: "{{ installer_directory | json_query('files[0].path') }}/inventory"
    mode: '0644'
  when:
    - use_advanced_inventory is not defined

- name: push advanced inventory file (mostly for aap-aa demo)
  ansible.builtin.template:
    src: templates/inventory-advanced.j2
    dest: "{{ installer_directory | json_query('files[0].path') }}/inventory"
    mode: '0644'
  when:
    - use_advanced_inventory is defined
    - use_advanced_inventory

- name: push ansible cfg for advanced installs
  ansible.builtin.copy:
    src: files/ansible.cfg
    dest: "{{ installer_directory | json_query('files[0].path') }}/ansible.cfg"
    mode: '0644'
  when:
    - use_advanced_inventory is defined
    - use_advanced_inventory

- name: run the setup playbook
  ansible.builtin.shell:
    cmd: ./setup.sh
  args:
    chdir: "{{ installer_directory | json_query('files[0].path') }}"
  when:
    - use_advanced_inventory is not defined

- name: run the setup playbook | advanced
  ansible.builtin.shell:
    cmd: ./setup.sh -- --forks 50
  args:
    chdir: "{{ installer_directory | json_query('files[0].path') }}"
  when:
    - use_advanced_inventory is defined
    - use_advanced_inventory