---

- name: find the installer directory
  ansible.builtin.find:
    paths: /tmp/aap-installer/
    patterns: "ansible*"
    file_type: directory
  register: installer_directory

- name: push our version of the inventory file
  ansible.builtin.template:
    src: templates/inventory.j2
    dest: "{{ installer_directory | json_query('files[0].path') }}/inventory"
    mode: '0644'

- name: run the setup playbook
  ansible.builtin.shell:
    cmd: ./setup.sh
  args:
    chdir: "{{ installer_directory | json_query('files[0].path') }}"