---

- name: add domain controller to forest
  hosts:
    - all
  pre_tasks:
     - name: set DNS client settings
       ansible.windows.win_dns_client:
        adapter_names: 'Ethernet*'
        dns_servers:
          - "{{ pdc_ip_address }}"
          - 127.0.0.1
  tasks:
    - name: confgure domain controllers
      ansible.windows.win_domain_controller:
        dns_domain_name: "{{ dns_zone }}"
        domain_admin_user: "{{ ansible_user }}@{{ dns_zone }}"
        domain_admin_password: "{{ ansible_password }}"
        safe_mode_password: "{{ ansible_password }}"
        state: domain_controller
      notify: reboot
  handlers:
    - name: reboot if needed
      ansible.windows.win_reboot:
      listen:
        - reboot