---

- name: build image from blueprint
  hosts:
    - all
  vars:
    blueprint_dir: /tmp
  pre_tasks:
    - name: Add user to weldr group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: weldr
        append: true
      become: true
  tasks:
    - name: create blueprint
      osbuild.composer.create_blueprint:
        dest: "{{ blueprint_dir }}/{{ blueprint.name }}-{{ blueprint.version }}.toml"
        name: "{{ blueprint.name }}"
        version: "{{ blueprint.version }}"
        packages: "{{ blueprint.packages }}"
        customizations: "{{ blueprint.customizations }}"
    - name: push the blueprint into image builder
      osbuild.composer.push_blueprint:
        src: "{{ blueprint_dir }}/{{ blueprint.name }}-{{ blueprint.version }}.toml"
    - name: build image
      osbuild.composer.start_compose:
        blueprint: "{{ blueprint.name }}"
        compose_type: "edge-commit"
      register: compose_start_out

    - name: print out compose info
      ansible.builtin.debug:
        var: compose_start_out

    - name: wait for compose to finish
      osbuild.composer.wait_compose:
        compose_id: "{{ compose_start_out['result']['build_id'] }}"

    - name: export the compose artifact
      osbuild.composer.export_compose:
        compose_id: "{{ compose_start_out['result']['build_id'] }}"
        dest: "/tmp/composer-compose.tar"