---

- name: setup demo context
  hosts:
    - all
  gather_facts: no
  pre_tasks:
    - name: get auth token for netbox
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/users/tokens/provision/"
        validate_certs: no
        method: POST
        status_code: 201
        body_format: json
        body:
          username: "{{ netbox_username }}"
          password: "{{ netbox_password }}"
      register: netbox_auth_token_raw
    - name: set netbox token fact
      ansible.builtin.set_fact:
        netbox_token: "{{ netbox_auth_token_raw.json.key }}"
  roles:
    - ../roles/manage_demo_context
  