---

- name: configure ansible automation hub
  hosts:
    - all
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ansible_connection: local
    ah_host: "{{ inventory_hostname }}"
  roles:
    - redhat_cop.ah_configuration.group
    - redhat_cop.ah_configuration.user
    - redhat_cop.ah_configuration.namespace
    - jjaswanson4.ah_configuration.publish
  tasks:
    - name: approve pending collections
      redhat_cop.ah_configuration.ah_approval:
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        validate_certs: "{{ ah_validate_certs }}"
        namespace: "{{ collection.namespace }}"
        name: "{{ collection.collection_name }}"
        version: "{{ collection.version }}"
      loop_control:
        loop_var: collection
      loop: "{{ ah_collections }}"

