---

- name: configure GitLab
  hosts:
    - all
  gather_facts: no
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: create GitLab groups
      community.general.gitlab_group:
        api_url: "{{ gitlab_api_url }}"
        api_username: "{{ gitlab_api_username }}"
        api_password: "{{ gitlab_api_password }}"
        validate_certs: "{{ gitlab_api_validate_certs }}"
        name: "{{ group.name }}"
        #path: "{{ group.path | default(omit) }}"
        #state: "{{ group.state | default('present') }}"
        #visibility: "{{ group.visibility }}"
      loop_control:
        loop_var: group
      loop: "{{ gitlab_groups }}"
      when:
        - gitlab_groups is defined
    - name: create GitLab projects
      community.general.gitlab_project:
        api_url: "{{ gitlab_api_url }}"
        api_username: "{{ gitlab_api_username }}"
        api_password: "{{ gitlab_api_password }}"
        validate_certs: "{{ gitlab_api_validate_certs }}"
        name: "{{ project.name }}"
        path: "{{ project.path }}"
        group: "{{ project.group | default(omit) }}"
      loop_control:
        loop_var: project
      loop: "{{ gitlab_projects }}"
      when:
        - gitlab_projects is defined