---

- name: configure ansible automation hub
  hosts:
    - all
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ansible_connection: local
  roles:
    - redhat_cop.ah_configuration.group
    - redhat_cop.ah_configuration.user
    - redhat_cop.ah_configuration.namespace
  tasks:
    - name: include role to upload collection directly from source control
      ansible.builtin.include_role:
        name: ../roles/upload_ansible_collection
      vars:
        collection: "{{ ansible_collection }}"
      when:
        - ansible_collection.url is defined
      loop_control:
        loop_var: ansible_collection
      loop: "{{ ah_collections }}"

    - name: upload collections
      jjaswanson4.ah_configuration.ah_collection:
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_verify_ssl: "{{ ah_validate_certs }}"
        name: "{{ collection.name }}"
        namespace: "{{ collection.namespace }}"
        path: "{{ collection.path }}"
        version: "{{ collection.version | default(omit) }}"
        auto_approve: "{{ collection.auto_approve }}"
      loop_control:
        loop_var: collection
      loop: "{{ ah_collections }}"
      when:
        - collection.path is defined