---

- name: configure demo inventory on controller
  hosts:
    - all
  gather_facts: no
  vars:
    controller_hosts_to_add: []
    controller_groups_to_add: []
  pre_tasks:
    - name: create unique id for demo if not existing
      block:
        - name: create unique id for demo instance
          ansible.builtin.shell:
            cmd: uuidgen | cut -c1-4
          register: demo_uuid_raw
        - name: set unique id fact
          ansible.builtin.set_fact:
            demo_uuid: "{{ demo_uuid_raw.stdout }}"
      when:
        - demo_uuid is not defined
    - name: load demo provisioner vars into tmp var
      ansible.builtin.include_vars:
        file: "vars/demos/{{ demo }}/provisioner.yml"
    - name: set inventories facts
      ansible.builtin.set_fact:
        controller_inventories:
          - name: "{{ audience }} - {{ demo }} Infrastructure"
            organization: "{{ controller_organization }}"
            variables: "{{ lookup('file', 'vars/controller/inventories.yml') | from_yaml }}"
    - name: force ansible to instanciate vars
      ansible.builtin.set_fact:      
        controller_inventories: "{{ lookup('vars', 'controller_inventories')"
    - name: add inventory to hosts
      ansible.builtin.set_fact:
        controller_hosts_to_add: "{{ controller_hosts_to_add + [ host | combine( { 'inventory': audience + ' - ' + demo + ' Infrastructure'} ) ] }}"
      loop_control:
        loop_var: host
      loop: "{{ controller_hosts }}"
    - name: build list of groups
      ansible.builtin.set_fact:
        controller_groups_to_add: "{{ controller_groups_to_add | default('[]') + [ group | combine( { 'inventory': audience + ' - ' + demo + ' Infrastructure' } ) ] }}"
      loop_control:
        loop_var: group
      loop: "{{ controller_groups }}"
    - name: load in satellite vars and group
      block:
        - name: set satellite host and group facts
          ansible.builtin.set_fact:
            satellite_host:
              - name: "{{ audience | lower }}-{{ demo }}-satellite.{{ demo_uuid }}.{{ base_dns_suffix }}"
                inventory: "{{ audience }} - {{ demo }} Infrastructure"
                variables: "{{ lookup('file', 'vars/demos/' + demo + '/satellite.yml') | from_yaml }}"
            satellite_group:
              - name: satellite
                inventory: "{{ audience }} - {{ demo }} Infrastructure"
                hosts:
                  - "{{ audience | lower }}-{{ demo }}-satellite.{{ demo_uuid }}.{{ base_dns_suffix }}"
        - name: add satellite host to main list
          ansible.builtin.set_fact:
            controller_hosts_to_add: "{{ controller_hosts_to_add + satellite_host }}"
      when:
        - satellite_configuration_file is defined
    - name: load in controller vars and group
      block:
        - name: set controller host and group facts
          ansible.builtin.set_fact:
            controller_host:
              - name: "{{ audience | lower }}-{{ demo }}-controller.{{ demo_uuid }}.{{ base_dns_suffix }}"
                inventory: "{{ audience }} - {{ demo }} Infrastructure"
                variables: "{{ lookup('file', 'vars/demos/' + demo + '/controller.yml') | from_yaml }}"
            controller_group:
              - name: controller
                inventory: "{{ audience }} - {{ demo }} Infrastructure"
                hosts:
                  - "{{ audience | lower }}-{{ demo }}-controller.{{ demo_uuid }}.{{ base_dns_suffix }}"
        - name: add controller host to main list
          ansible.builtin.set_fact:
            controller_hosts_to_add: "{{ controller_hosts_to_add + controller_host }}"
      when:
        - controller_configuration_file is defined
    - name: define satellite group even if empty
      ansible.builtin.set_fact:
        satellite_group:
          - name: satellite
            inventory: "{{ audience }} - {{ demo }} Infrastructure"
      when:
        - satellite_configuration_file is not defined
    - name: define controller group even if empty
      ansible.builtin.set_fact:
        controller_group:
          - name: controller
            inventory: "{{ audience }} - {{ demo }} Infrastructure"
      when:
        - controller_configuration_file is not defined
    - name: load in management_plane group
      ansible.builtin.set_fact:
        management_plane_group:
          - name: management_plane
            inventory: "{{ audience }} - {{ demo }} Infrastructure"
            variables: "{{ lookup('file', 'vars/controller/groups.yml') | from_yaml }}"
            children:
              - controller
              - satellite
    - name: add up groups
      ansible.builtin.set_fact:
        controller_groups_to_add: "{{ controller_groups_to_add + satellite_group + controller_group + management_plane_group }}"
    - name: set vars for roles
      ansible.builtin.set_fact:
        controller_hosts: "{{ controller_hosts_to_add }}"
        controller_groups: "{{ controller_groups_to_add }}"
    - debug:
        msg: "{{ controller_hosts }}"
  roles:
   - redhat_cop.controller_configuration.inventories
   - redhat_cop.controller_configuration.hosts
   - redhat_cop.controller_configuration.groups