---

- name: create an inventory for edge devices in ansible controller
  hosts:
    - all
  gather_facts: false
  vars:
    ansible_connection: local
    controller_inventories:
      - name: "{{ audience }} Edge Systems"
        organization: "{{ audience }}"
        variables:
          audience: "{{ audience }}"
          demo: "{{ demo }}"
          demo_uuid: "{{ demo_uuid }}"
          edge_workload: "{{ edge_workload }}"
    controller_groups:
      - name: human_machine_interface
        inventory: "{{ audience }} Edge Systems"
        variables:
          system_type: hmi
          edge_management_group_name: Human_Machine_interfaces
      - name: process_control_system
        inventory: "{{ audience }} Edge Systems"
        variables:
          system_type: pcs
          edge_workload_info: "{{ edge_workload_info }}"
          edge_management_group_name: Process_Control_Systems
      - name: in_store_display
        inventory: "{{ audience }} Edge Systems"
        variables:
          system_type: isd
          display_website: "{{ display_website }}"
          edge_management_group_name: In-Store_Displays
  roles:
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.groups