---

- name: create manifest via RHSM API
  hosts:
    - all
  gather_facts: no
  pre_tasks:
    - name: print KB article
      ansible.builtin.debug:
        msg: This playbook is based off of https://access.redhat.com/articles/3626371
    - name: use an offline token to get a token
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ rhsm_token }}"
      register: get_access_token
    - name: set access_token fact
      ansible.builtin.set_fact:
        access_token: "{{ get_access_token.json.access_token }}"
  tasks:
    - name: create subscription allocation
      ansible.builtin.uri:
        url: https://api.access.redhat.com/management/v1/allocations
        headers:
          Authorization: Bearer {{ access_token }}
        method: POST
        body_format: json
        body:
          name: test123-manifest
          type: Satellite
          version: '6.9'