---

- name: create an inventory for edge devices in ansible controller
  hosts:
    - all
  gather_facts: false
  vars:
    controller_inventories:
      - name: "{{ audience }} Edge Systems"
        organization: "{{ audience }}"
        variables:
          audience: "{{ audience }}"
          demo_uuid: "{{ demo_uuid }}"
          kiosk_website: "{{ kiosk_website }}"
    controller_groups:
      - name: human_machine_interface
        inventory: "{{ audience }} Edge Systems"
      - name: process_control_system
        organization: "{{ audience }}"
        inventory: "{{ audience }} Edge Systems"
  roles:
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.groups