---

- name: get access token for c.rh.c API
  hosts:
    - all
  gather_facts: no
  roles:
    - ../roles/auth_with_console_dot

- name: create group for demo in edge management
  hosts:
    - all
  gather_facts: no
  module_defaults:
    ansible.builtin.uri:
      headers:
        accept: application/json
        Authorization: Bearer {{ console_dot_api_access_token }}
      return_content: yes
  tasks:
    - uri:
        url: https://console.redhat.com/api/edge/v1/device-groups
        body_format: json
        body:
          Name: "{{ demo_uuid }}"
          Type: static
        method: POST
        status_code:
          - 200
          - 400
      register: group_create_output
      changed_when:
        - "'CreatedAt' in group_create_output.content"
