---

- name: install hana
  hosts:
    - all
  pre_tasks:
    - name: check for existing HANA install
      ansible.builtin.shell:
        cmd: > 
          /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/sapcontrol
          -nr {{ sap_hana_deployment_hana_instance_number }}
          -function GetProcessList
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: hana_status
  tasks:
    - name: include hana deployment role
      ansible.builtin.include_role:
        name: redhat_sap.sap_hana_deployment
      when:
        - "'OK' not in hana_status.stdout"