---

- name: deploy workload to process control systems
  hosts:
    - process_control_system
  roles:
    - ../roles/deploy_process_control_workload


- name: deploy workload to HMI devices
  hosts:
    - human_machine_interface
  module_defaults:
    ansible.builtin.uri:
      force_basic_auth: yes
      user: "{{ controller_username }}"
      password: "{{ controller_password }}"
      validate_certs: "{{ controller_validate_certs }}"
  pre_tasks:
    - name: run API calls from localhost
      block:
        - name: get group info
          ansible.builtin.uri:
            url: "https://{{ controller_hostname }}/api/v2/groups?name=process_control_system"
          register: group_search
        - name: ensure group has a host
          ansible.builtin.uri:
            url: "https://{{ controller_hostname }}/api/v2/groups/{{ group_search.json.results[0].id }}/hosts"
          register: group_membership
          until:
            - group_membership.json.count | int == 1
          delay: 10
          retries: 50
      delegate_to: localhost  
      
    - name: set url for devices
      ansible.builtin.set_fact:
        kiosk_website: "http://{{ hostvars[groups['process_control_system'][0]]['ansible_host'] }}:1881/ui"
  tasks:
    - name: include kiosk setup role
      ansible.builtin.include_role:
        name: ../roles/deploy_kiosk_mode
        apply:
          become: true


- name: deploy workload to In-Store Displays
  hosts:
    - in_store_display
  # roles:
  #   - ../roles/deploy_edge_workload