---

- name: disconnect system from consoledot
  hosts:
    - all
  tasks:
    - name: disconnect insights
      ansible.builtin.shell:
        cmd: insights-client --unregister
      failed_when: false
    - name: disconnect red hat connector
      ansible.builtin.shell:
        cmd: rhc disconnect
      failed_when: false
