---

- name: disconnect system from consoledot
  hosts:
    - all
  tasks:
    - name: let tasks run and "fail" if needed
      block:
        - name: disconnect insights
          ansible.builtin.shell:
            cmd: insights-client --unregister
        - name: disconnect red hat connector
          ansible.builtin.shell:
            cmd: rhc disconnect
      failed_when: false
