---

- name: build out satellite
  hosts:
    - all
  roles:
    - ../roles/add_virtual_disk
    - jjaswanson4.setup_rhel_for_satellite.setup_storage
    - jjaswanson4.install_satellite.install_satellite
