---

- name: create group in Edge Management
  hosts:
    - all
  gather_facts: false
  tasks:
    - name: create group in Edge Management
      consoledot.edgemanagement.groups:
        name: "{{ demo_uuid }}"
        state: "{{ group_state | default('present') }}"
