---

- name: provision managed hosts
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: manage entries in CMDB
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - ../roles/manage_cmdb