---

- name: populate active directory with entities
  hosts:
    - all
  gather_facts: no
  vars:
    OU_Path: "{{ ['DC='] | product(dns_zone | upper | split('.')) | map('join') | join(',') }}"
    Group_OU: "OU=Groups,{{ OU_Path }}"
  tasks:
    - name: create OU in AD
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
              [String]
              $OU_Path
          )
          New-ADOrganizationalUnit -Name "Groups" -Path $OU_Path
        parameters:
          OU_Path: "{{ OU_Path }}"
    - name: create groups in AD
      community.windows.win_domain_group:
        name: "{{ group.name }}"
        ou: "{{ Group_OU }}"
        scope: "{{ group.scope | default('global') }}"
      loop: "{{ ad.groups }}"
      loop_control:
        loop_var: group
    - name: create users in AD
      community.windows.win_domain_user:
        name: "{{ user.name }}"
        upn: "{{ user.name }}@{{ dns_zone }}"
        groups: "{{ user.groups | default(omit) }}"
        password: "{{ user.password | default(admin_password) }}"
        password_never_expires: yes
      loop: "{{ ad.users }}"
      loop_control:
        loop_var: user