---

- name: run various post-install steps on r4e systems
  hosts:
    - all
  pre_tasks:
    - name: set the system hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: set the system timezone
      community.general.timezone:
        name: America/Chicago
    - name: install an out-of-band package
      community.general.rpm_ostree_pkg:
        name: https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm
      notify:
        - reboot_system
  tasks:
    - name: create kiosk users group
      ansible.builtin.group:
        name: kiosk-users
        gid: 2048
      notify:
        - reboot_system
    - name: create kiosk user
      ansible.builtin.user:
        name: kiosk-user
        uid: 2048
        group: kiosk-users
        password: '$6$R3dh4t123$cYAI8okOB5I/cozPAatzNBBPwKOhnEAxaseIaTKuQWcYg.Js2ce3ZCtRK/nj9wmIBc17Y3e/Jm2Do/r6CBvwG/'
      notify:
        - reboot_system
    - name: enable auto-login for kiosk user
      ansible.builtin.blockinfile:
        path: /etc/gdm/custom.conf
        insertafter: '\[daemon\]'
        block: |
          AutomaticLoginEnable=True
          AutomaticLogin=kiosk-user
      notify:
        - reboot_system
    - name: configure kiosk-user to use the kiosk session
      ansible.builtin.blockinfile:
        path: /var/lib/AccountsService/users/kiosk-user
        insertafter: '\[User\]'
        create: yes
        block: |
          Session=com.redhat.Kiosk
          SystemAccount=false
      notify:
        - reboot_system
    - name: create kiosk service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/kiosk.service
        content: |
          [Unit]
          Description=kiosk firefox service
          After=graphical.target

          [Service]
          Type=simple
          User=kiosk-user
          Environment="DISPLAY=:0"
          ExecStartPre=/usr/bin/sleep 10
          ExecStart=/usr/bin/firefox -kiosk https://time.gov
          Restart=on-failure
          RestartSec=1
          TimeoutSec=60
          RuntimeMaxSec=infinity

          [Install]
          WantedBy=multi-user.target
      notify:
        - reboot_system
    - name: enable the service
      ansible.builtin.systemd:
        name: kiosk.service
        enabled: yes
  post_tasks:
    - name: check the status of the system
      ansible.builtin.shell:
        cmd: rpm-ostree status
      register: rpm_ostree_status
    - name: print out rpm-ostree status
      ansible.builtin.debug:
        msg: "{{ rpm_ostree_status.stdout_lines }}"
  handlers:
    - name: reboot system
      ansible.builtin.reboot:
        reboot_command: systemctl reboot
      listen:
        - reboot_system