---

- name: run various post-install steps on r4e systems
  hosts:
    - all
  tasks:
    - name: set the system hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: set the system timezone
      community.general.timezone:
        name: America/Chicago
    - name: install an out-of-band package
      community.general.rpm_ostree_pkg:
        name: https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/htop-3.0.5-1.el8.x86_64.rpm
      register: packages_installed
    - name: reboot system if packages changed
      ansible.builtin.reboot:
        reboot_command: systemctl reboot
  post_tasks:
    - name: check the status of the system
      ansible.builtin.shell:
        cmd: rpm-ostree status
      register: rpm_ostree_status
    - name: print out rpm-ostree status
      ansible.builtin.debug:
        msg: "{{ rpm_ostree_status.stdout_lines }}"
      