---

- name: provision a rhel for edge VM
  hosts:
    - all
  gather_facts: no
  tasks:
    - name: provision rhel for edge system
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        datastore: "{{ vcenter_datastore }}"
        folder: "/Demos/{{ demo_uuid }}/"
        name: "r4e-system-{{ system_number }}.{{ demo_uuid }}.{{ base_dns_suffix }}"
        state: poweredon
        guest_id: rhel8_64Guest
        disk:
          - size_gb: 10
            type: thin
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: vlan146
            device_type: vmxnet3
        cdrom:
          - controller_number: 0
            controller_type: sata
            iso_path: '[{{ vcenter_datastore }}] iso/{{ demo_uuid }}-edge-installer.iso'
            type: iso
            unit_number: 0
        # wait_for_ip_address: true
        # wait_for_ip_address_timeout: 600
      register: deploy_vm
      loop_control:
        loop_var: system_number
        pause: 10
      loop: "{{ range(0, 5, 1) | list }}"

