---

- name: remove demo inventory
  hosts:
    - all
  gather_facts: no
  pre_tasks:
    - name: set inventories facts
      ansible.builtin.set_fact:
        controller_inventories:
          - name: "{{ audience }} - {{ demo }} Infrastructure"
            organization: "{{ controller_organization }}"
            state: absent
  roles:
   - redhat_cop.controller_configuration.inventories