---

- name: run demo provisioner workflow
  hosts:
    - all
  gather_facts: no
  vars_files:
    - vars/demos.yml
  pre_tasks:
    - name: match demo to display name
      ansible.builtin.set_fact:
        demo_display_name: "{{ demos.display_name }}"
      when:
        - demo == demos.name
      loop_control:
        loop_var: demos
      loop: "{{ available_demos }}"
    - name: set workflow to run | provision
      ansible.builtin.set_fact:
        workflow_to_run: Provision
      when:
        - demo_state is not defined or
          demo_state == 'present'
    - name: set workflow to run | teardown
      ansible.builtin.set_fact:
        workflow_to_run: Teardown
      when:
        - demo_state == 'absent'
    - name: set workflow to run | reset
      ansible.builtin.set_fact:
        workflow_to_run: Reset
      when:
          demo_state == 'reset'
    - name: set demo provisioner workflow facts
      ansible.builtin.set_fact:
        controller_workflow_launch_jobs:
          - name: "{{ workflow_to_run }} {{ demo_display_name }} Demo"
            inventory: "{{ audience }} - {{ demo }} Infrastructure"
            wait: "{{ wait_for_workflow | default(false) }}"
            extra_vars:
              audience: "{{ audience }}"
              demo_uuid: "{{ demo_uuid }}"
              demo_state: "{{ demo_state | default('present') }}"
              demo_context_state: "{{ demo_context_state | default('present') }}"
  roles:
    - redhat_cop.controller_configuration.workflow_launch