---

- name: initial setup of SAP hosts
  hosts:
    - all
  become: no
  roles:
    - ../roles/mount_nfs_shares
    - redhat.rhel_system_roles.storage
    - sap.rhel.preconfigure
    - redhat_sap.sap_hostagent
  handlers:
    - name: reboot system
      ansible.builtin.reboot:
      listen:
        - __sap_preconfigure_reboot_handler