---

- name: send email to provisioner
  hosts:
    - all
  gather_facts: false
  pre_tasks:
    - name: build failure message
      ansible.builtin.set_fact:
        provisioner_status: failed
        failure_message: "Provisioning failed at step: {{ failed_at_step }}"
      when:
        - failed_at_step is defined
    - name: build success message
      block:
        - name: build success message parts
          ansible.builtin.set_fact:
            satellite_url: "https://{{ audience | lower }}-{{ demo }}-satellite.{{ demo_uuid }}.{{ base_dns_suffix }}"
            controller_url: "https://{{ audience | lower }}-{{ demo }}-controller.{{ demo_uuid }}.{{ base_dns_suffix }}"
        - name: build success message from parts
          ansible.builtin.set_fact:
            success_message: |
              Demo information:
              ---
              Demo UUID: {{ demo_uuid }}
              Demo Satellite URL: {{ satellite_url }}
              Demo Controller URL: {{ controller_url }}
      when:
        - failed_at_step is not defined
        - provisioner_status == 'success'
  tasks:
    - name: send email with the provisioner status of "{{ provisioner_status }}"
      community.general.mail: 
        host: smtp.redhat.com
        to: "{{ provisioner }} <{{ provisioner_email }}>"
        from: Demo Provisioner <dont@email.me>
        subject: Demo Provisioning {{ provisioner_status }}
        body: >
          Hello {{ provisioner }},

          {{ demo_display_name }} demo for {{ audience }} has completed with state: {{ provisioner_status }}

          {{ failure_message | default(success_message) }}

          - The Demo Provisioner