---

- name: send email to provisioner
  hosts:
    - all
  gather_facts: false
  pre_tasks:
    - name: build failure message if needed
      ansible.builtin.set_fact:
        provisioner_status: failed
        failure_message: "Provisioning failed at step: {{ failed_at_step }}"
      when:
        - failed_at_step is defined
  tasks:
    - name: send email with the provisioner status of "{{ provisioner_status }}"
      community.general.mail: 
        host: smtp.redhat.com
        to: "{{ provisioner }} <{{ provisioner_email }}>"
        from: Demo Provisioner <dont@email.me>
        subject: Demo Provisioning {{ provisioner_status }}
        body: >
          Hello {{ provisioner }},

          {{ demo }} demo for {{ audience }} has completed with state: {{ provisioner_status }}

          {{ failure_message | default(omit) }}

          - The Demo Provisioner