---

- name: configure an instance of controller to provision {{ demo }} demo
  hosts:
    - localhost
  gather_facts: no
  vars:
    resources_path: vars
    controller_resources: "{{ resources_path }}/controller/"
    controller_hostname: "{{ controller.hostname }}"
    controller_username: "{{ controller.username }}"
    controller_password: "{{ controller.password }}"
    controller_validate_certs: "{{ controller.validate_certs | default(false) }}"
    controller_configuration_credentials_secure_logging: no
    controller_configuration_projects_async_retries: 60
    controller_configuration_projects_async_delay: 5
  vars_files:
    - vars/demos.yml
  pre_tasks:
    - name: validate selected demo
      ansible.builtin.assert:
        that:
          - demo in available_demos | json_query('[*].name')
        success_msg: "{{ demo }} demo selected"
        fail_msg: "selected demo {{ demo }} is not available, please select one of: {{ available_demos | join(', ') }}"

    - name: load in standard controller configs
      ansible.builtin.include_vars:
        dir: "{{ controller_resources }}"
        extensions:
          - yml
        ignore_files:
          - inventories.yml
          - workflow-survey.yml
          - groups/*

    - name: configure controller with standard configs
      ansible.builtin.include_role:
        name: "{{ controller_config_role }}"
      loop:
        - redhat_cop.controller_configuration.organizations
        - redhat_cop.controller_configuration.credential_types
        - redhat_cop.controller_configuration.credentials
        - redhat_cop.controller_configuration.execution_environments
        - redhat_cop.controller_configuration.projects
        - redhat_cop.controller_configuration.job_templates
        - redhat_cop.controller_configuration.workflow_job_templates
      loop_control:
        loop_var: controller_config_role

  tasks:
    - name: load in {{ demo }} provisioner vars
      ansible.builtin.include_vars:
        file: "vars/demos/{{ demo }}/provisioner.yml"

    - name: configure controller with demo specific configs
      ansible.builtin.include_role:
        name: "{{ controller_config_role }}"
      loop:
        - redhat_cop.controller_configuration.organizations
        - redhat_cop.controller_configuration.credential_types
        - redhat_cop.controller_configuration.credentials
        - redhat_cop.controller_configuration.execution_environments
        - redhat_cop.controller_configuration.projects
        - redhat_cop.controller_configuration.job_templates
        - redhat_cop.controller_configuration.workflow_job_templates
      loop_control:
        loop_var: controller_config_role