---

- name: delete deployed systems
  hosts:
    - all
  gather_facts: false
  tasks:
    - name: delete systems from satellite
      redhat.satellite.host:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_url }}"
        validate_certs: "{{ satellite_validate_certs | default('false') }}"
        name: "{{ inventory_hostname }}"
        state: absent
      delegate_to: localhost
      throttle: 2
