---

name: Test Demos
on: [push]
jobs:
  ansible-lint:
    name: Use ansible-lint to check code
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List out requirements
        run: >
          cat ${{ github.workspace }}/execution-environment/requirements.yml
      - name: Install required roles
        run: >
          export ANSIBLE_CONFIG=~/ansible.cfg &&
          ansible-galaxy install
          --role-file ${{ github.workspace }}/execution-environment/requirements.yml
          --roles-path ${{ github.workspace }}/.ansible/roles
      - name: Install required collections
        run: >
          export ANSIBLE_CONFIG=~/ansible.cfg &&
          ansible-galaxy collection install
          --requirements-file ${{ github.workspace }}/execution-environment/requirements.yml
          --collections-path ${{ github.workspace }}/.ansible/collections
      - name: Run ansible-lint
        run: >
          export DEFAULT_ROLES_PATH=${{ github.workspace }}/.ansible/roles &&
          export COLLECTIONS_PATHS=${{ github.workspace }}/.ansible/collections &&
          ls -l $DEFAULT_ROLES_PATH &&
          ls -l $COLLECTIONS_PATHS &&
          ansible-lint
          -c ${{ github.workspace }}/.ansible-lint
          -p ${{ github.workspace }}/playbooks ${{ github.workspace }}/roles
  cicd-complete:
    name: Report CI/CD completed successfully
    runs-on: self-hosted
    needs:
      - ansible-lint
    steps:
      - name: Report success
        run: >
          echo "CI/CD pipeline complete"
