---

name: Test Demos
on: [push]
jobs:
  ansible-lint:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: create a directory for roles/collections
        run: |
          mkdir .ansible
      - run: >
          cat ${{ github.workspace }}/execution-environment/requirements.yml
      - name: Install required roles
        run: >
         export ANSIBLE_CONFIG=~/ansible.cfg &&
          ansible-galaxy install
          --role-file ${{ github.workspace }}/execution-environment/requirements.yml
          --roles-path ${{ github.workspace }}/.ansible/
      - name: Install required collections
        run: >
         export ANSIBLE_CONFIG=~/ansible.cfg &&
          ansible-galaxy collection install
          --requirements-file ${{ github.workspace }}/execution-environment/requirements.yml
          --collections-path ${{ github.workspace }}/.ansible/
      # - name: Test provisioning demo (check controller for details)
      #   run: >
      #     ansible-playbook ${{ github.workspace }}/tests/test-demo.yml
      #     --extra-vars "demo=patching"
      #     --extra-vars "demo_uuid=${{ github.run_id }}"
      - name: Report provisioning success
        run: echo "Provisioning successful."
      # - name: Teardown demo
      #   run: >
      #     ansible-playbook ${{ github.workspace }}/tests/teardown.yml
      #     --extra-vars "demo=patching"
      #     --extra-vars "demo_uuid=${{ github.run_id }}"
      - name: Report teardown success
        run: echo "Teardown successful."
  # Test-IDM-AD-Integration-Demo:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - name: Report success
  #       run: "echo ${{ github.run_id }}"