---

galaxy_info:
  author: Josh Swanson
  description: manage dns records in red hat idm
  license: GPL-3.0
  min_ansible_version: 2.9
  galaxy_tags:
    - virtualization
    - vmware
    - cloud
    - systems_management

dependencies: []